# Generate only Uzbek data; preserve existing Russian/English IPA.
from pathlib import Path
import json, subprocess
root=Path(__file__).resolve().parent.parent
keys={line.split('|')[0] for line in (root/'src/vocabulary-source.txt').read_text(encoding='utf-8-sig').splitlines() if line and not line.startswith('#')}
rows={}
for line in (root/'src/vocabulary-uz-source.txt').read_text(encoding='utf-8-sig').splitlines():
    if not line.strip():continue
    key,word=line.split('|')
    assert key not in rows,key
    # eSpeak Uzbek recognizes ASCII apostrophes in o'/g'.
    text=word.replace('‘',"'").replace('’',"'")
    ipa=subprocess.check_output(['espeak-ng','-q','--ipa','-v','uz',text],text=True).strip().replace('\n',' ')
    rows[key]={'uz':word,'uzIPA':ipa}
assert set(rows)==keys, 'Uzbek translations must cover every vocabulary key'
(root/'src/vocabulary-uz.js').write_text('// Uzbek Latin translations; approximate IPA generated by eSpeak NG.\nexport const uzbek = '+json.dumps(rows,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print('Generated',len(rows),'Uzbek entries')
