"""Rebuild static vocabulary and approximate IPA; needs espeak-ng only at build time."""
from pathlib import Path
import json, subprocess
root=Path(__file__).resolve().parent.parent
rows=[]
for line in (root/'src/vocabulary-source.txt').read_text(encoding='utf-8-sig').splitlines():
    if line.startswith('#'):
        weight=int(line[1:]);continue
    if not line.strip():continue
    en,ru=line.split('|')
    def ipa(word,voice):
        return subprocess.check_output(['espeak-ng','-q','--ipa','-v',voice,word],text=True).strip().replace('\n',' ').replace('  ',' ')
    rows.append(dict(ru=ru,en=en,weight=weight,ruIPA=ipa(ru,'ru'),enIPA=ipa(en,'en-us')))
assert len(rows)==1000
(root/'src/vocabulary.js').write_text('// Approximate IPA generated by eSpeak NG; source: vocabulary-source.txt.\nexport const vocabulary = '+json.dumps(rows,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print('Generated',len(rows),'words with Russian and English IPA')
