// Uzbek Latin translations; approximate IPA generated by eSpeak NG.
export const uzbek = {
  "cat": {
    "uz": "mushuk",
    "uzIPA": "mˈʊʃʊk"
  },
  "dog": {
    "uz": "it",
    "uzIPA": "ˈyt"
  },
  "house": {
    "uz": "uy",
    "uzIPA": "ˈʊj"
  },
  "sun": {
    "uz": "quyosh",
    "uzIPA": "qˈʊjɑʃ"
  },
  "water": {
    "uz": "suv",
    "uzIPA": "sˈʊʋ"
  },
  "bread": {
    "uz": "non",
    "uzIPA": "nˈɑn"
  },
  "apple": {
    "uz": "olma",
    "uzIPA": "ˈɑɫmæ"
  },
  "book": {
    "uz": "kitob",
    "uzIPA": "kˈytɑb"
  },
  "milk": {
    "uz": "sut",
    "uzIPA": "sˈʊt"
  },
  "friend": {
    "uz": "do‘st",
    "uzIPA": "dˈost"
  },
  "tree": {
    "uz": "daraxt",
    "uzIPA": "dˈæɾæχt"
  },
  "fish": {
    "uz": "baliq",
    "uzIPA": "bˈæɫyq"
  },
  "bird": {
    "uz": "qush",
    "uzIPA": "qˈʊʃ"
  },
  "car": {
    "uz": "mashina",
    "uzIPA": "mæʃˈynæ"
  },
  "bus": {
    "uz": "avtobus",
    "uzIPA": "æʋtˈɑbʊs"
  },
  "bed": {
    "uz": "karavot",
    "uzIPA": "kæɾˈæʋɑt"
  },
  "door": {
    "uz": "eshik",
    "uzIPA": "ˈeʃyk"
  },
  "window": {
    "uz": "deraza",
    "uzIPA": "deɾˈæzæ"
  },
  "table": {
    "uz": "stol",
    "uzIPA": "stˈɑɫ"
  },
  "chair": {
    "uz": "stul",
    "uzIPA": "stˈʊɫ"
  },
  "cup": {
    "uz": "chashka",
    "uzIPA": "tSˈæʃkæ"
  },
  "plate": {
    "uz": "likopcha",
    "uzIPA": "ɫykˈɑptSæ"
  },
  "spoon": {
    "uz": "qoshiq",
    "uzIPA": "qˈɑʃyq"
  },
  "fork": {
    "uz": "sanchqi",
    "uzIPA": "sˈæntSqy"
  },
  "knife": {
    "uz": "pichoq",
    "uzIPA": "pˈytSɑq"
  },
  "egg": {
    "uz": "tuxum",
    "uzIPA": "tˈʊχʊm"
  },
  "rice": {
    "uz": "guruch",
    "uzIPA": "ɡˈʊɾʊtS"
  },
  "meat": {
    "uz": "go‘sht",
    "uzIPA": "ɡˈoʃt"
  },
  "soup": {
    "uz": "sho‘rva",
    "uzIPA": "ʃˈoɾʋæ"
  },
  "tea": {
    "uz": "choy",
    "uzIPA": "tSˈɑj"
  },
  "coffee": {
    "uz": "qahva",
    "uzIPA": "qˈæhʋæ"
  },
  "juice": {
    "uz": "sharbat",
    "uzIPA": "ʃˈæɾbæt"
  },
  "salt": {
    "uz": "tuz",
    "uzIPA": "tˈʊz"
  },
  "sugar": {
    "uz": "shakar",
    "uzIPA": "ʃˈækæɾ"
  },
  "cheese": {
    "uz": "pishloq",
    "uzIPA": "pˈyʃɫɑq"
  },
  "butter": {
    "uz": "sariyog‘",
    "uzIPA": "sæɾˈyjɑʁ"
  },
  "cake": {
    "uz": "tort",
    "uzIPA": "tˈɑɾt"
  },
  "banana": {
    "uz": "banan",
    "uzIPA": "bˈænæn"
  },
  "orange": {
    "uz": "apelsin",
    "uzIPA": "æpˈeɫsyn"
  },
  "lemon": {
    "uz": "limon",
    "uzIPA": "ɫˈymɑn"
  },
  "potato": {
    "uz": "kartoshka",
    "uzIPA": "kæɾtˈɑʃkæ"
  },
  "tomato": {
    "uz": "pomidor",
    "uzIPA": "pɑmˈydɑɾ"
  },
  "onion": {
    "uz": "piyoz",
    "uzIPA": "pˈyjɑz"
  },
  "carrot": {
    "uz": "sabzi",
    "uzIPA": "sˈæbzy"
  },
  "hand": {
    "uz": "qo‘l panjasi",
    "uzIPA": "qˈoɫ pændʒˈæsy"
  },
  "head": {
    "uz": "bosh",
    "uzIPA": "bˈɑʃ"
  },
  "eye": {
    "uz": "ko‘z",
    "uzIPA": "kˈoz"
  },
  "ear": {
    "uz": "quloq",
    "uzIPA": "qˈʊɫɑq"
  },
  "nose": {
    "uz": "burun",
    "uzIPA": "bˈʊɾʊn"
  },
  "mouth": {
    "uz": "og‘iz",
    "uzIPA": "ˈɑʁyz"
  },
  "leg": {
    "uz": "oyoq",
    "uzIPA": "ˈɑjɑq"
  },
  "arm": {
    "uz": "qo‘l",
    "uzIPA": "qˈoɫ"
  },
  "foot": {
    "uz": "oyoq panjasi",
    "uzIPA": "ˈɑjɑq pændʒˈæsy"
  },
  "hair": {
    "uz": "soch",
    "uzIPA": "sˈɑtS"
  },
  "face": {
    "uz": "yuz",
    "uzIPA": "jˈʊz"
  },
  "boy": {
    "uz": "o‘g‘il bola",
    "uzIPA": "ˈoʁyɫ bˈɑlæ"
  },
  "girl": {
    "uz": "qiz bola",
    "uzIPA": "qˈyz bˈɑlæ"
  },
  "man": {
    "uz": "erkak",
    "uzIPA": "ˈeɾkæk"
  },
  "woman": {
    "uz": "ayol",
    "uzIPA": "ˈæjɑɫ"
  },
  "baby": {
    "uz": "chaqaloq",
    "uzIPA": "tSæqˈæɫɑq"
  },
  "mother": {
    "uz": "ona",
    "uzIPA": "ˈɑnæ"
  },
  "father": {
    "uz": "ota",
    "uzIPA": "ˈɑtæ"
  },
  "sister": {
    "uz": "opa-singil",
    "uzIPA": "ˈɑpæsˈyŋyɫ"
  },
  "brother": {
    "uz": "aka-uka",
    "uzIPA": "ˈækæˈʊkæ"
  },
  "family": {
    "uz": "oila",
    "uzIPA": "ɑˈylæ"
  },
  "home": {
    "uz": "turar joy",
    "uzIPA": "tˈʊɾæɾ dʒˈɑj"
  },
  "school": {
    "uz": "maktab",
    "uzIPA": "mˈæktæb"
  },
  "park": {
    "uz": "istirohat bog‘i",
    "uzIPA": "ˌystyɾˈɑhæt bˈɑʁy"
  },
  "shop": {
    "uz": "do‘kon",
    "uzIPA": "dˈokɑn"
  },
  "street": {
    "uz": "ko‘cha",
    "uzIPA": "kˈotSæ"
  },
  "city": {
    "uz": "shahar",
    "uzIPA": "ʃˈæhæɾ"
  },
  "room": {
    "uz": "xona",
    "uzIPA": "χˈɑnæ"
  },
  "bag": {
    "uz": "sumka",
    "uzIPA": "sˈʊmkæ"
  },
  "hat": {
    "uz": "shlyapa",
    "uzIPA": "ʃɫjˈæpæ"
  },
  "shoe": {
    "uz": "botinka",
    "uzIPA": "bɑtˈynkæ"
  },
  "shirt": {
    "uz": "ko‘ylak",
    "uzIPA": "kˈojlæk"
  },
  "coat": {
    "uz": "palto",
    "uzIPA": "pˈæɫtɑ"
  },
  "sock": {
    "uz": "paypoq",
    "uzIPA": "pˈæjpɑq"
  },
  "ball": {
    "uz": "to‘p",
    "uzIPA": "tˈop"
  },
  "toy": {
    "uz": "o‘yinchoq",
    "uzIPA": "ojˈyntSɑq"
  },
  "pen": {
    "uz": "ruchka",
    "uzIPA": "ɾˈʊtSkæ"
  },
  "pencil": {
    "uz": "qalam",
    "uzIPA": "qˈælæm"
  },
  "paper": {
    "uz": "qog‘oz",
    "uzIPA": "qˈɑʁɑz"
  },
  "box": {
    "uz": "quti",
    "uzIPA": "qˈʊty"
  },
  "key": {
    "uz": "kalit",
    "uzIPA": "kˈæɫyt"
  },
  "clock": {
    "uz": "soat",
    "uzIPA": "sˈɑæt"
  },
  "phone": {
    "uz": "telefon",
    "uzIPA": "telˈefˌɑn"
  },
  "lamp": {
    "uz": "chiroq",
    "uzIPA": "tSˈyɾɑq"
  },
  "moon": {
    "uz": "oy",
    "uzIPA": "ˈɑj"
  },
  "star": {
    "uz": "yulduz",
    "uzIPA": "jˈʊɫdʊz"
  },
  "sky": {
    "uz": "osmon",
    "uzIPA": "ˈɑsmɑn"
  },
  "rain": {
    "uz": "yomg‘ir",
    "uzIPA": "jˈɑmʁyɾ"
  },
  "snow": {
    "uz": "qor",
    "uzIPA": "qˈɑɾ"
  },
  "wind": {
    "uz": "shamol",
    "uzIPA": "ʃˈæmɑɫ"
  },
  "fire": {
    "uz": "olov",
    "uzIPA": "ˈɑɫɑʋ"
  },
  "ice": {
    "uz": "muz",
    "uzIPA": "mˈʊz"
  },
  "sea": {
    "uz": "dengiz",
    "uzIPA": "dˈeŋyz"
  },
  "river": {
    "uz": "daryo",
    "uzIPA": "dˈæɾjɑ"
  },
  "flower": {
    "uz": "gul",
    "uzIPA": "ɡˈʊɫ"
  },
  "grass": {
    "uz": "o‘t",
    "uzIPA": "ˈot"
  },
  "red": {
    "uz": "qizil",
    "uzIPA": "qˈyzyɫ"
  },
  "blue": {
    "uz": "ko‘k",
    "uzIPA": "kˈok"
  },
  "green": {
    "uz": "yashil",
    "uzIPA": "jˈæʃyɫ"
  },
  "yellow": {
    "uz": "sariq",
    "uzIPA": "sˈæɾyq"
  },
  "white": {
    "uz": "oq",
    "uzIPA": "ˈɑq"
  },
  "black": {
    "uz": "qora",
    "uzIPA": "qˈɑɾæ"
  },
  "brown": {
    "uz": "jigarrang",
    "uzIPA": "dʒyɡˈæɾɾæŋ"
  },
  "pink": {
    "uz": "pushti",
    "uzIPA": "pˈʊʃty"
  },
  "gray": {
    "uz": "kulrang",
    "uzIPA": "kˈʊɫɾæŋ"
  },
  "purple": {
    "uz": "binafsharang",
    "uzIPA": "bˈynæfʃˌæɾæŋ"
  },
  "big": {
    "uz": "katta",
    "uzIPA": "kˈættæ"
  },
  "small": {
    "uz": "kichik",
    "uzIPA": "kˈytSyk"
  },
  "long": {
    "uz": "uzun",
    "uzIPA": "ˈʊzʊn"
  },
  "short": {
    "uz": "qisqa",
    "uzIPA": "qˈysqæ"
  },
  "high": {
    "uz": "baland",
    "uzIPA": "bˈælænd"
  },
  "low": {
    "uz": "past",
    "uzIPA": "pˈæst"
  },
  "hot": {
    "uz": "issiq",
    "uzIPA": "ˈyssyq"
  },
  "cold": {
    "uz": "sovuq",
    "uzIPA": "sˈɑʋʊq"
  },
  "warm": {
    "uz": "iliq",
    "uzIPA": "ˈyɫyq"
  },
  "cool": {
    "uz": "salqin",
    "uzIPA": "sˈæɫqyn"
  },
  "new": {
    "uz": "yangi",
    "uzIPA": "jˈæŋy"
  },
  "old": {
    "uz": "eski",
    "uzIPA": "ˈesky"
  },
  "young": {
    "uz": "yosh",
    "uzIPA": "jˈɑʃ"
  },
  "good": {
    "uz": "yaxshi",
    "uzIPA": "jˈæχʃy"
  },
  "bad": {
    "uz": "yomon",
    "uzIPA": "jˈɑmɑn"
  },
  "happy": {
    "uz": "baxtli",
    "uzIPA": "bˈæχtɫy"
  },
  "sad": {
    "uz": "g‘amgin",
    "uzIPA": "ʁˈæmɡyn"
  },
  "angry": {
    "uz": "jahldor",
    "uzIPA": "dʒˈæhɫdɑɾ"
  },
  "kind": {
    "uz": "mehribon",
    "uzIPA": "mehɾˈybɑn"
  },
  "nice": {
    "uz": "yoqimli",
    "uzIPA": "jɑqˈymɫy"
  },
  "fast": {
    "uz": "tez",
    "uzIPA": "tˈez"
  },
  "slow": {
    "uz": "sekin",
    "uzIPA": "sˈekyn"
  },
  "easy": {
    "uz": "oson",
    "uzIPA": "ˈɑsɑn"
  },
  "hard": {
    "uz": "qiyin",
    "uzIPA": "qˈyjyn"
  },
  "clean": {
    "uz": "toza",
    "uzIPA": "tˈɑzæ"
  },
  "dirty": {
    "uz": "iflos",
    "uzIPA": "ˈyfɫˌɑs"
  },
  "full": {
    "uz": "to‘la",
    "uzIPA": "tˈolæ"
  },
  "empty": {
    "uz": "bo‘sh",
    "uzIPA": "bˈoʃ"
  },
  "wet": {
    "uz": "ho‘l",
    "uzIPA": "hˈoɫ"
  },
  "dry": {
    "uz": "quruq",
    "uzIPA": "qˈʊɾʊq"
  },
  "sweet": {
    "uz": "shirin",
    "uzIPA": "ʃˈyɾyn"
  },
  "sour": {
    "uz": "nordon",
    "uzIPA": "nˈɑɾdɑn"
  },
  "soft": {
    "uz": "yumshoq",
    "uzIPA": "jˈʊmʃɑq"
  },
  "strong": {
    "uz": "kuchli",
    "uzIPA": "kˈʊtSɫy"
  },
  "weak": {
    "uz": "zaif",
    "uzIPA": "zˈæyf"
  },
  "rich": {
    "uz": "boy",
    "uzIPA": "bˈɑj"
  },
  "poor": {
    "uz": "kambag‘al",
    "uzIPA": "kæmbˈæʁæɫ"
  },
  "loud": {
    "uz": "baland ovozli",
    "uzIPA": "bˈælænd ɑʋˈɑzɫy"
  },
  "quiet": {
    "uz": "sokin",
    "uzIPA": "sˈɑkyn"
  },
  "bright": {
    "uz": "yorqin",
    "uzIPA": "jˈɑɾqyn"
  },
  "dark": {
    "uz": "qorong‘i",
    "uzIPA": "qɑɾˈɑŋʔy"
  },
  "beautiful": {
    "uz": "chiroyli",
    "uzIPA": "tSyɾˈɑjɫy"
  },
  "ugly": {
    "uz": "xunuk",
    "uzIPA": "χˈʊnʊk"
  },
  "hungry": {
    "uz": "och",
    "uzIPA": "ˈɑtS"
  },
  "thirsty": {
    "uz": "chanqagan",
    "uzIPA": "tSænqˈæɡæn"
  },
  "tired": {
    "uz": "charchagan",
    "uzIPA": "tSæɾtSˈæɡæn"
  },
  "sick": {
    "uz": "kasal",
    "uzIPA": "kˈæsæɫ"
  },
  "healthy": {
    "uz": "sog‘lom",
    "uzIPA": "sˈɑʁɫɑm"
  },
  "ready": {
    "uz": "tayyor",
    "uzIPA": "tˈæjjɑɾ"
  },
  "busy": {
    "uz": "band",
    "uzIPA": "bˈænd"
  },
  "free": {
    "uz": "erkin",
    "uzIPA": "ˈeɾkyn"
  },
  "safe": {
    "uz": "xavfsiz",
    "uzIPA": "χˈæʋfsˌyz"
  },
  "open": {
    "uz": "ochiq",
    "uzIPA": "ˈɑtSyq"
  },
  "closed": {
    "uz": "yopiq",
    "uzIPA": "jˈɑpyq"
  },
  "one": {
    "uz": "bir",
    "uzIPA": "bˈyɾ"
  },
  "two": {
    "uz": "ikki",
    "uzIPA": "ˈykky"
  },
  "three": {
    "uz": "uch",
    "uzIPA": "ˈʊtS"
  },
  "four": {
    "uz": "to‘rt",
    "uzIPA": "tˈoɾt"
  },
  "five": {
    "uz": "besh",
    "uzIPA": "bˈeʃ"
  },
  "six": {
    "uz": "olti",
    "uzIPA": "ˈɑɫty"
  },
  "seven": {
    "uz": "yetti",
    "uzIPA": "jˈetty"
  },
  "eight": {
    "uz": "sakkiz",
    "uzIPA": "sˈækkyz"
  },
  "nine": {
    "uz": "to‘qqiz",
    "uzIPA": "tˈoqqyz"
  },
  "ten": {
    "uz": "o‘n",
    "uzIPA": "ˈon"
  },
  "eleven": {
    "uz": "o‘n bir",
    "uzIPA": "ˈon bˈyɾ"
  },
  "twelve": {
    "uz": "o‘n ikki",
    "uzIPA": "ˈon ˈykky"
  },
  "twenty": {
    "uz": "yigirma",
    "uzIPA": "jyɡˈyɾmæ"
  },
  "hundred": {
    "uz": "yuz",
    "uzIPA": "jˈʊz"
  },
  "morning": {
    "uz": "ertalab",
    "uzIPA": "eɾtˈælæb"
  },
  "afternoon": {
    "uz": "tushdan keyin",
    "uzIPA": "tˈʊʃdæn kˌejyn"
  },
  "evening": {
    "uz": "kechqurun",
    "uzIPA": "ketSqˈʊɾʊn"
  },
  "night": {
    "uz": "tun",
    "uzIPA": "tˈʊn"
  },
  "day": {
    "uz": "kun",
    "uzIPA": "kˈʊn"
  },
  "week": {
    "uz": "hafta",
    "uzIPA": "hˈæftˌæ"
  },
  "month": {
    "uz": "oy",
    "uzIPA": "ˈɑj"
  },
  "year": {
    "uz": "yil",
    "uzIPA": "jˈyɫ"
  },
  "today": {
    "uz": "bugun",
    "uzIPA": "bˈʊɡʊn"
  },
  "tomorrow": {
    "uz": "ertaga",
    "uzIPA": "eɾtˈæɡæ"
  },
  "yesterday": {
    "uz": "kecha",
    "uzIPA": "kˈetSæ"
  },
  "now": {
    "uz": "hozir",
    "uzIPA": "hˈɑzyɾ"
  },
  "soon": {
    "uz": "tez orada",
    "uzIPA": "tˈez ɑɾˈædæ"
  },
  "here": {
    "uz": "bu yerda",
    "uzIPA": "bʊ jˈeɾdæ"
  },
  "there": {
    "uz": "u yerda",
    "uzIPA": "ʊ jˈeɾdæ"
  },
  "always": {
    "uz": "har doim",
    "uzIPA": "hˈæɾ dˈɑym"
  },
  "never": {
    "uz": "hech qachon",
    "uzIPA": "hˈetS qˈætSɑn"
  },
  "often": {
    "uz": "tez-tez",
    "uzIPA": "tˈeztˈez"
  },
  "sometimes": {
    "uz": "ba’zan",
    "uzIPA": "bˈæʔzæn"
  },
  "again": {
    "uz": "yana",
    "uzIPA": "jˈænæ"
  },
  "together": {
    "uz": "birga",
    "uzIPA": "bˈyɾɡæ"
  },
  "alone": {
    "uz": "yolg‘iz",
    "uzIPA": "jˈɑɫʁyz"
  },
  "run": {
    "uz": "yugurmoq",
    "uzIPA": "jʊɡˈʊɾmɑq"
  },
  "walk": {
    "uz": "piyoda yurmoq",
    "uzIPA": "pyjˈɑdæ jˈʊɾmɑq"
  },
  "jump": {
    "uz": "sakramoq",
    "uzIPA": "sækɾˈæmɑq"
  },
  "swim": {
    "uz": "suzmoq",
    "uzIPA": "sˈʊzmɑq"
  },
  "fly": {
    "uz": "uchmoq",
    "uzIPA": "ˈʊtSmɑq"
  },
  "sit": {
    "uz": "o‘tirmoq",
    "uzIPA": "otˈyɾmɑq"
  },
  "stand": {
    "uz": "tik turmoq",
    "uzIPA": "tˈyk tˈʊɾmɑq"
  },
  "sleep": {
    "uz": "uxlamoq",
    "uzIPA": "ʊχlˈæmɑq"
  },
  "wake": {
    "uz": "uyg‘onmoq",
    "uzIPA": "ʊjʁˈɑnmɑq"
  },
  "eat": {
    "uz": "ovqat yemoq",
    "uzIPA": "ˈɑʋqæt jˈemɑq"
  },
  "drink": {
    "uz": "ichmoq",
    "uzIPA": "ˈytSmɑq"
  },
  "cook": {
    "uz": "ovqat pishirmoq",
    "uzIPA": "ˈɑʋqæt pyʃˈyɾmɑq"
  },
  "wash": {
    "uz": "yuvmoq",
    "uzIPA": "jˈʊʋmɑq"
  },
  "read": {
    "uz": "o‘qimoq",
    "uzIPA": "oqˈymɑq"
  },
  "write": {
    "uz": "yozmoq",
    "uzIPA": "jˈɑzmɑq"
  },
  "speak": {
    "uz": "gapirmoq",
    "uzIPA": "ɡæpˈyɾmɑq"
  },
  "listen": {
    "uz": "tinglamoq",
    "uzIPA": "tyŋlˈæmɑq"
  },
  "hear": {
    "uz": "eshitmoq",
    "uzIPA": "eʃˈytmɑq"
  },
  "see": {
    "uz": "ko‘rmoq",
    "uzIPA": "kˈoɾmɑq"
  },
  "look": {
    "uz": "qaramoq",
    "uzIPA": "qæɾˈæmɑq"
  },
  "watch": {
    "uz": "kuzatmoq",
    "uzIPA": "kʊzˈætmɑq"
  },
  "smell": {
    "uz": "hid sezmoq",
    "uzIPA": "hˈyd sˈezmɑq"
  },
  "touch": {
    "uz": "tegmoq",
    "uzIPA": "tˈeɡmɑq"
  },
  "think": {
    "uz": "o‘ylamoq",
    "uzIPA": "ojlˈæmɑq"
  },
  "know": {
    "uz": "bilmoq",
    "uzIPA": "bˈyɫmɑq"
  },
  "learn": {
    "uz": "o‘rganmoq",
    "uzIPA": "oɾɡˈænmɑq"
  },
  "teach": {
    "uz": "o‘rgatmoq",
    "uzIPA": "oɾɡˈætmɑq"
  },
  "study": {
    "uz": "o‘rganib chiqmoq",
    "uzIPA": "oɾɡˈænyb tSˈyqmɑq"
  },
  "work": {
    "uz": "ishlamoq",
    "uzIPA": "yʃlˈæmɑq"
  },
  "play": {
    "uz": "o‘ynamoq",
    "uzIPA": "ojnˈæmɑq"
  },
  "sing": {
    "uz": "kuylamoq",
    "uzIPA": "kʊjlˈæmɑq"
  },
  "dance": {
    "uz": "raqsga tushmoq",
    "uzIPA": "ɾˈæqsɡæ tˈʊʃmɑq"
  },
  "laugh": {
    "uz": "kulmoq",
    "uzIPA": "kˈʊɫmɑq"
  },
  "cry": {
    "uz": "yig‘lamoq",
    "uzIPA": "jyʁlˈæmɑq"
  },
  "smile": {
    "uz": "tabassum",
    "uzIPA": "tæbˈæssʊm"
  },
  "love": {
    "uz": "sevmoq",
    "uzIPA": "sˈeʋmɑq"
  },
  "like": {
    "uz": "yoqmoq",
    "uzIPA": "jˈɑqmɑq"
  },
  "want": {
    "uz": "xohlamoq",
    "uzIPA": "χɑhlˈæmɑq"
  },
  "need": {
    "uz": "muhtoj bo‘lmoq",
    "uzIPA": "mˈʊhtɑdʒ bˈoɫmɑq"
  },
  "help": {
    "uz": "yordam bermoq",
    "uzIPA": "jˈɑɾdæm bˈeɾmɑq"
  },
  "give": {
    "uz": "bermoq",
    "uzIPA": "bˈeɾmɑq"
  },
  "take": {
    "uz": "olmoq",
    "uzIPA": "ˈɑɫmɑq"
  },
  "bring": {
    "uz": "olib kelmoq",
    "uzIPA": "ˈɑɫyb kˈeɫmɑq"
  },
  "carry": {
    "uz": "ko‘tarib bormoq",
    "uzIPA": "kotˈæɾyb bˈɑɾmɑq"
  },
  "buy": {
    "uz": "sotib olmoq",
    "uzIPA": "sˈɑtyb ˈɑɫmɑq"
  },
  "sell": {
    "uz": "sotmoq",
    "uzIPA": "sˈɑtmɑq"
  },
  "pay": {
    "uz": "to‘lamoq",
    "uzIPA": "tolˈæmɑq"
  },
  "find": {
    "uz": "topmoq",
    "uzIPA": "tˈɑpmɑq"
  },
  "lose": {
    "uz": "yo‘qotmoq",
    "uzIPA": "joqˈɑtmɑq"
  },
  "keep": {
    "uz": "saqlamoq",
    "uzIPA": "sæqlˈæmɑq"
  },
  "leave": {
    "uz": "tark etmoq",
    "uzIPA": "tˈæɾk ˈetmɑq"
  },
  "come": {
    "uz": "kelmoq",
    "uzIPA": "kˈeɫmɑq"
  },
  "go": {
    "uz": "bormoq",
    "uzIPA": "bˈɑɾmɑq"
  },
  "arrive": {
    "uz": "yetib kelmoq",
    "uzIPA": "jˈetyb kˈeɫmɑq"
  },
  "return": {
    "uz": "qaytmoq",
    "uzIPA": "qˈæjtmɑq"
  },
  "start": {
    "uz": "boshlamoq",
    "uzIPA": "bɑʃlˈæmɑq"
  },
  "finish": {
    "uz": "tugatmoq",
    "uzIPA": "tʊɡˈætmɑq"
  },
  "stop": {
    "uz": "to‘xtatmoq",
    "uzIPA": "toχtˈætmɑq"
  },
  "wait": {
    "uz": "kutmoq",
    "uzIPA": "kˈʊtmɑq"
  },
  "ask": {
    "uz": "so‘ramoq",
    "uzIPA": "soɾˈæmɑq"
  },
  "answer": {
    "uz": "javob bermoq",
    "uzIPA": "dʒˈæʋɑb bˈeɾmɑq"
  },
  "call": {
    "uz": "qo‘ng‘iroq qilmoq",
    "uzIPA": "qoŋʔˈyɾɑq qˈyɫmɑq"
  },
  "meet": {
    "uz": "uchratmoq",
    "uzIPA": "ʊtSɾˈætmɑq"
  },
  "visit": {
    "uz": "tashrif buyurmoq",
    "uzIPA": "tˈæʃɾyf bʊjˈʊɾmɑq"
  },
  "live": {
    "uz": "yashamoq",
    "uzIPA": "jæʃˈæmɑq"
  },
  "stay": {
    "uz": "qolmoq",
    "uzIPA": "qˈɑɫmɑq"
  },
  "move": {
    "uz": "harakatlanmoq",
    "uzIPA": "hˌæɾækætlˈænmɑq"
  },
  "turn": {
    "uz": "burilmoq",
    "uzIPA": "bʊɾˈyɫmɑq"
  },
  "push": {
    "uz": "itarmoq",
    "uzIPA": "ytˈæɾmɑq"
  },
  "pull": {
    "uz": "tortmoq",
    "uzIPA": "tˈɑɾtmɑq"
  },
  "throw": {
    "uz": "uloqtirmoq",
    "uzIPA": "ˌʊɫɑqtˈyɾmɑq"
  },
  "catch": {
    "uz": "tutmoq",
    "uzIPA": "tˈʊtmɑq"
  },
  "kick": {
    "uz": "tepmoq",
    "uzIPA": "tˈepmɑq"
  },
  "hit": {
    "uz": "urmoq",
    "uzIPA": "ˈʊɾmɑq"
  },
  "cut": {
    "uz": "kesmoq",
    "uzIPA": "kˈesmɑq"
  },
  "break": {
    "uz": "sindirmoq",
    "uzIPA": "syndˈyɾmɑq"
  },
  "build": {
    "uz": "qurmoq",
    "uzIPA": "qˈʊɾmɑq"
  },
  "fix": {
    "uz": "tuzatmoq",
    "uzIPA": "tʊzˈætmɑq"
  },
  "draw": {
    "uz": "rasm chizmoq",
    "uzIPA": "ɾˈæsm tSˈyzmɑq"
  },
  "paint": {
    "uz": "bo‘yamoq",
    "uzIPA": "bojˈæmɑq"
  },
  "count": {
    "uz": "sanamoq",
    "uzIPA": "sænˈæmɑq"
  },
  "choose": {
    "uz": "tanlamoq",
    "uzIPA": "tænlˈæmɑq"
  },
  "try": {
    "uz": "sinab ko‘rmoq",
    "uzIPA": "sˈynæb kˈoɾmɑq"
  },
  "use": {
    "uz": "foydalanmoq",
    "uzIPA": "fˌɑjdælˈænmɑq"
  },
  "wear": {
    "uz": "kiyib yurmoq",
    "uzIPA": "kˈyjyb jˈʊɾmɑq"
  },
  "hold": {
    "uz": "ushlamoq",
    "uzIPA": "ʊʃlˈæmɑq"
  },
  "fall": {
    "uz": "yiqilmoq",
    "uzIPA": "jyqˈyɫmɑq"
  },
  "climb": {
    "uz": "tirmashib chiqmoq",
    "uzIPA": "tyɾmˈæʃyb tSˈyqmɑq"
  },
  "ride": {
    "uz": "minib yurmoq",
    "uzIPA": "mˈynyb jˈʊɾmɑq"
  },
  "drive": {
    "uz": "mashina haydamoq",
    "uzIPA": "mæʃˈynæ hæjdˈæmɑq"
  },
  "send": {
    "uz": "yubormoq",
    "uzIPA": "jʊbˈɑɾmɑq"
  },
  "show": {
    "uz": "ko‘rsatmoq",
    "uzIPA": "koɾsˈætmɑq"
  },
  "share": {
    "uz": "bo‘lishmoq",
    "uzIPA": "boɫˈyʃmɑq"
  },
  "remember": {
    "uz": "eslamoq",
    "uzIPA": "eslˈæmɑq"
  },
  "forget": {
    "uz": "unutmoq",
    "uzIPA": "ʊnˈʊtmɑq"
  },
  "understand": {
    "uz": "tushunmoq",
    "uzIPA": "tʊʃˈʊnmɑq"
  },
  "believe": {
    "uz": "ishonmoq",
    "uzIPA": "yʃˈɑnmɑq"
  },
  "hope": {
    "uz": "umid qilmoq",
    "uzIPA": "ˈʊmyd qˈyɫmɑq"
  },
  "change": {
    "uz": "o‘zgartirmoq",
    "uzIPA": "ˌozɡæɾtˈyɾmɑq"
  },
  "grow": {
    "uz": "o‘smoq",
    "uzIPA": "ˈosmɑq"
  },
  "airport": {
    "uz": "aeroport",
    "uzIPA": "ˌæeɾˈɑpɑɾt"
  },
  "station": {
    "uz": "bekat",
    "uzIPA": "bˈekæt"
  },
  "ticket": {
    "uz": "chipta",
    "uzIPA": "tSˈyptæ"
  },
  "train": {
    "uz": "poyezd",
    "uzIPA": "pˈɑjezd"
  },
  "plane": {
    "uz": "samolyot",
    "uzIPA": "sæmˈɑɫjɑt"
  },
  "bicycle": {
    "uz": "velosiped",
    "uzIPA": "ʋˌeɫɑsˈyped"
  },
  "scooter": {
    "uz": "samokat",
    "uzIPA": "sæmˈɑkæt"
  },
  "boat": {
    "uz": "qayiq",
    "uzIPA": "qˈæjyq"
  },
  "ship": {
    "uz": "kema",
    "uzIPA": "kˈemæ"
  },
  "truck": {
    "uz": "yuk mashinasi",
    "uzIPA": "jˈʊk mˌæʃynˈæsy"
  },
  "taxi": {
    "uz": "taksi",
    "uzIPA": "tˈæksy"
  },
  "road": {
    "uz": "yo‘l",
    "uzIPA": "jˈoɫ"
  },
  "bridge": {
    "uz": "ko‘prik",
    "uzIPA": "kˈopɾyk"
  },
  "traffic": {
    "uz": "transport harakati",
    "uzIPA": "tɾˈænspɑɾt hˌæɾækˈæty"
  },
  "map": {
    "uz": "xarita",
    "uzIPA": "χæɾˈytæ"
  },
  "hotel": {
    "uz": "mehmonxona",
    "uzIPA": "mˌehmɑnχˈɑnæ"
  },
  "beach": {
    "uz": "plyaj",
    "uzIPA": "pɫjˈædʒ"
  },
  "island": {
    "uz": "orol",
    "uzIPA": "ˈɑɾɑɫ"
  },
  "mountain": {
    "uz": "tog‘",
    "uzIPA": "tˈɑʁ"
  },
  "forest": {
    "uz": "o‘rmon",
    "uzIPA": "ˈoɾmɑn"
  },
  "village": {
    "uz": "qishloq",
    "uzIPA": "qˈyʃɫɑq"
  },
  "country": {
    "uz": "mamlakat",
    "uzIPA": "mæmlˈækæt"
  },
  "capital": {
    "uz": "poytaxt",
    "uzIPA": "pˈɑjtæχt"
  },
  "address": {
    "uz": "manzil",
    "uzIPA": "mˈænzyɫ"
  },
  "passport": {
    "uz": "pasport",
    "uzIPA": "pˈæspɑɾt"
  },
  "suitcase": {
    "uz": "chamadon",
    "uzIPA": "tSæmˈædɑn"
  },
  "journey": {
    "uz": "sayohat",
    "uzIPA": "sæjˈɑhæt"
  },
  "holiday": {
    "uz": "bayram",
    "uzIPA": "bˈæjɾæm"
  },
  "weekend": {
    "uz": "dam olish kunlari",
    "uzIPA": "dˈæm ˈɑɫyʃ kʊnlˈæɾy"
  },
  "spring": {
    "uz": "bahor",
    "uzIPA": "bˈæhɑɾ"
  },
  "summer": {
    "uz": "yoz",
    "uzIPA": "jˈɑz"
  },
  "autumn": {
    "uz": "kuz",
    "uzIPA": "kˈʊz"
  },
  "winter": {
    "uz": "qish",
    "uzIPA": "qˈyʃ"
  },
  "weather": {
    "uz": "ob-havo",
    "uzIPA": "ˈɑbhˈæʋɑ"
  },
  "cloud": {
    "uz": "bulut",
    "uzIPA": "bˈʊɫʊt"
  },
  "storm": {
    "uz": "bo‘ron",
    "uzIPA": "bˈoɾɑn"
  },
  "fog": {
    "uz": "tuman",
    "uzIPA": "tˈʊmæn"
  },
  "lake": {
    "uz": "ko‘l",
    "uzIPA": "kˈoɫ"
  },
  "field": {
    "uz": "dala",
    "uzIPA": "dˈælæ"
  },
  "farm": {
    "uz": "ferma",
    "uzIPA": "fˈeɾmæ"
  },
  "horse": {
    "uz": "ot",
    "uzIPA": "ˈɑt"
  },
  "cow": {
    "uz": "sigir",
    "uzIPA": "sˈyɡyɾ"
  },
  "sheep": {
    "uz": "qo‘y",
    "uzIPA": "qˈoj"
  },
  "goat": {
    "uz": "echki",
    "uzIPA": "ˈetSky"
  },
  "pig": {
    "uz": "cho‘chqa",
    "uzIPA": "tSˈotSqæ"
  },
  "chicken": {
    "uz": "tovuq",
    "uzIPA": "tˈɑʋʊq"
  },
  "duck": {
    "uz": "o‘rdak",
    "uzIPA": "ˈoɾdæk"
  },
  "rabbit": {
    "uz": "quyon",
    "uzIPA": "qˈʊjɑn"
  },
  "mouse": {
    "uz": "sichqon",
    "uzIPA": "sˈytSqɑn"
  },
  "lion": {
    "uz": "sher",
    "uzIPA": "ʃˈeɾ"
  },
  "tiger": {
    "uz": "yo‘lbars",
    "uzIPA": "jˈoɫbæɾs"
  },
  "bear": {
    "uz": "ayiq",
    "uzIPA": "ˈæjyq"
  },
  "wolf": {
    "uz": "bo‘ri",
    "uzIPA": "bˈoɾy"
  },
  "fox": {
    "uz": "tulki",
    "uzIPA": "tˈʊɫky"
  },
  "elephant": {
    "uz": "fil",
    "uzIPA": "fˈyɫ"
  },
  "monkey": {
    "uz": "maymun",
    "uzIPA": "mˈæjmʊn"
  },
  "snake": {
    "uz": "ilon",
    "uzIPA": "ˈyɫɑn"
  },
  "frog": {
    "uz": "qurbaqa",
    "uzIPA": "qʊɾbˈæqæ"
  },
  "bee": {
    "uz": "asalari",
    "uzIPA": "ˌæsælˈæɾy"
  },
  "butterfly": {
    "uz": "kapalak",
    "uzIPA": "kæpˈælæk"
  },
  "ant": {
    "uz": "chumoli",
    "uzIPA": "tSʊmˈɑɫy"
  },
  "spider": {
    "uz": "o‘rgimchak",
    "uzIPA": "oɾɡˈymtSæk"
  },
  "turtle": {
    "uz": "toshbaqa",
    "uzIPA": "tɑʃbˈæqæ"
  },
  "whale": {
    "uz": "kit",
    "uzIPA": "kˈyt"
  },
  "dolphin": {
    "uz": "delfin",
    "uzIPA": "dˈeɫfˌyn"
  },
  "shark": {
    "uz": "akula",
    "uzIPA": "ækˈʊlæ"
  },
  "kitchen": {
    "uz": "oshxona",
    "uzIPA": "ɑʃχˈɑnæ"
  },
  "bathroom": {
    "uz": "hammom",
    "uzIPA": "hˈæmmɑm"
  },
  "bedroom": {
    "uz": "yotoqxona",
    "uzIPA": "jˌɑtɑqχˈɑnæ"
  },
  "garden": {
    "uz": "bog‘",
    "uzIPA": "bˈɑʁ"
  },
  "roof": {
    "uz": "tom",
    "uzIPA": "tˈɑm"
  },
  "wall": {
    "uz": "devor",
    "uzIPA": "dˈeʋɑɾ"
  },
  "floor": {
    "uz": "pol",
    "uzIPA": "pˈɑɫ"
  },
  "ceiling": {
    "uz": "shift",
    "uzIPA": "ʃˈyft"
  },
  "stairs": {
    "uz": "zina",
    "uzIPA": "zˈynæ"
  },
  "sofa": {
    "uz": "divan",
    "uzIPA": "dˈyʋæn"
  },
  "mirror": {
    "uz": "ko‘zgu",
    "uzIPA": "kˈozɡʊ"
  },
  "shelf": {
    "uz": "tokcha",
    "uzIPA": "tˈɑktSæ"
  },
  "carpet": {
    "uz": "gilam",
    "uzIPA": "ɡˈylæm"
  },
  "pillow": {
    "uz": "yostiq",
    "uzIPA": "jˈɑstyq"
  },
  "blanket": {
    "uz": "ko‘rpa",
    "uzIPA": "kˈoɾpæ"
  },
  "towel": {
    "uz": "sochiq",
    "uzIPA": "sˈɑtSyq"
  },
  "soap": {
    "uz": "sovun",
    "uzIPA": "sˈɑʋʊn"
  },
  "brush": {
    "uz": "cho‘tka",
    "uzIPA": "tSˈotkæ"
  },
  "comb": {
    "uz": "taroq",
    "uzIPA": "tˈæɾɑq"
  },
  "toothbrush": {
    "uz": "tish cho‘tkasi",
    "uzIPA": "tˈyʃ tSotkˈæsy"
  },
  "fridge": {
    "uz": "muzlatkich",
    "uzIPA": "mʊzlˈætkytS"
  },
  "oven": {
    "uz": "pech",
    "uzIPA": "pˈetS"
  },
  "kettle": {
    "uz": "choynak",
    "uzIPA": "tSˈɑjnæk"
  },
  "bottle": {
    "uz": "shisha idish",
    "uzIPA": "ʃˈyʃæ ˈydyʃ"
  },
  "bowl": {
    "uz": "kosa",
    "uzIPA": "kˈɑsæ"
  },
  "pan": {
    "uz": "tova",
    "uzIPA": "tˈɑʋæ"
  },
  "basket": {
    "uz": "savat",
    "uzIPA": "sˈæʋæt"
  },
  "bucket": {
    "uz": "chelak",
    "uzIPA": "tSˈelæk"
  },
  "rope": {
    "uz": "arqon",
    "uzIPA": "ˈæɾqɑn"
  },
  "ladder": {
    "uz": "narvon",
    "uzIPA": "nˈæɾʋɑn"
  },
  "fence": {
    "uz": "panjara",
    "uzIPA": "pændʒˈæɾæ"
  },
  "gate": {
    "uz": "darvoza",
    "uzIPA": "dæɾʋˈɑzæ"
  },
  "yard": {
    "uz": "hovli",
    "uzIPA": "hˈɑʋɫy"
  },
  "neighbor": {
    "uz": "qo‘shni",
    "uzIPA": "qˈoʃny"
  },
  "doctor": {
    "uz": "shifokor",
    "uzIPA": "ʃyfˈɑkɑɾ"
  },
  "nurse": {
    "uz": "hamshira",
    "uzIPA": "hæmʃˈyɾæ"
  },
  "teacher": {
    "uz": "o‘qituvchi",
    "uzIPA": "ˌoqytˈʊʋtSy"
  },
  "student": {
    "uz": "talaba",
    "uzIPA": "tælˈæbæ"
  },
  "driver": {
    "uz": "haydovchi",
    "uzIPA": "hæjdˈɑʋtSy"
  },
  "farmer": {
    "uz": "fermer",
    "uzIPA": "fˈeɾmeɾ"
  },
  "baker": {
    "uz": "novvoy",
    "uzIPA": "nˈɑʋʋɑj"
  },
  "chef": {
    "uz": "bosh oshpaz",
    "uzIPA": "bˈɑʃ ˈɑʃpæz"
  },
  "waiter": {
    "uz": "ofitsiant",
    "uzIPA": "ɑfˌytsˈyænt"
  },
  "artist": {
    "uz": "rassom",
    "uzIPA": "ɾˈæssɑm"
  },
  "singer": {
    "uz": "xonanda",
    "uzIPA": "χɑnˈændæ"
  },
  "actor": {
    "uz": "aktyor",
    "uzIPA": "ˈæktjɑɾ"
  },
  "writer": {
    "uz": "yozuvchi",
    "uzIPA": "jɑzˈʊʋtSy"
  },
  "engineer": {
    "uz": "muhandis",
    "uzIPA": "mʊhˈændys"
  },
  "scientist": {
    "uz": "olim",
    "uzIPA": "ˈɑɫym"
  },
  "police": {
    "uz": "politsiya",
    "uzIPA": "pˌɑɫytsˈyjæ"
  },
  "firefighter": {
    "uz": "o‘t o‘chiruvchi",
    "uzIPA": "ˈot ˌotSyɾˈʊʋtSy"
  },
  "soldier": {
    "uz": "askar",
    "uzIPA": "ˈæskæɾ"
  },
  "lawyer": {
    "uz": "huquqshunos",
    "uzIPA": "hˌʊqʊqʃˈʊnɑs"
  },
  "manager": {
    "uz": "rahbar",
    "uzIPA": "ɾˈæhbæɾ"
  },
  "customer": {
    "uz": "xaridor",
    "uzIPA": "χæɾˈydɑɾ"
  },
  "patient": {
    "uz": "bemor",
    "uzIPA": "bˈemɑɾ"
  },
  "hospital": {
    "uz": "shifoxona",
    "uzIPA": "ʃyfˌɑχˈɑnæ"
  },
  "medicine": {
    "uz": "dori",
    "uzIPA": "dˈɑɾy"
  },
  "health": {
    "uz": "salomatlik",
    "uzIPA": "sˌæɫɑmˈætɫyk"
  },
  "pain": {
    "uz": "og‘riq",
    "uzIPA": "ˈɑʁɾyq"
  },
  "fever": {
    "uz": "isitma",
    "uzIPA": "ysˈytmæ"
  },
  "cough": {
    "uz": "yo‘tal",
    "uzIPA": "jˈotæɫ"
  },
  "blood": {
    "uz": "qon",
    "uzIPA": "qˈɑn"
  },
  "heart": {
    "uz": "yurak",
    "uzIPA": "jˈʊɾæk"
  },
  "brain": {
    "uz": "miya",
    "uzIPA": "mˈyjæ"
  },
  "stomach": {
    "uz": "oshqozon",
    "uzIPA": "ɑʃqˈɑzɑn"
  },
  "back": {
    "uz": "orqa",
    "uzIPA": "ˈɑɾqæ"
  },
  "neck": {
    "uz": "bo‘yin",
    "uzIPA": "bˈojyn"
  },
  "shoulder": {
    "uz": "yelka",
    "uzIPA": "jˈeɫkæ"
  },
  "knee": {
    "uz": "tizza",
    "uzIPA": "tˈyzzæ"
  },
  "finger": {
    "uz": "qo‘l barmog‘i",
    "uzIPA": "qˈoɫ bæɾmˈɑʁy"
  },
  "tooth": {
    "uz": "tish",
    "uzIPA": "tˈyʃ"
  },
  "skin": {
    "uz": "teri",
    "uzIPA": "tˈeɾy"
  },
  "bone": {
    "uz": "suyak",
    "uzIPA": "sˈʊjæk"
  },
  "money": {
    "uz": "pul",
    "uzIPA": "pˈʊɫ"
  },
  "price": {
    "uz": "narx",
    "uzIPA": "nˈæɾχ"
  },
  "cost": {
    "uz": "qiymat",
    "uzIPA": "qˈyjmæt"
  },
  "cash": {
    "uz": "naqd pul",
    "uzIPA": "nˈæqd pˈʊɫ"
  },
  "coin": {
    "uz": "tanga",
    "uzIPA": "tˈæŋæ"
  },
  "bank": {
    "uz": "bank",
    "uzIPA": "bˈænk"
  },
  "wallet": {
    "uz": "hamyon",
    "uzIPA": "hˈæmjɑn"
  },
  "bill": {
    "uz": "to‘lov hisobi",
    "uzIPA": "tˈoɫɑʋ hysˈɑby"
  },
  "gift": {
    "uz": "sovg‘a",
    "uzIPA": "sˈɑʋʁæ"
  },
  "market": {
    "uz": "bozor",
    "uzIPA": "bˈɑzɑɾ"
  },
  "restaurant": {
    "uz": "restoran",
    "uzIPA": "ɾestˈɑɾæn"
  },
  "breakfast": {
    "uz": "nonushta",
    "uzIPA": "nɑnˈʊʃtæ"
  },
  "lunch": {
    "uz": "tushlik",
    "uzIPA": "tˈʊʃɫyk"
  },
  "dinner": {
    "uz": "kechki ovqat",
    "uzIPA": "kˈetSky ˈɑʋqæt"
  },
  "meal": {
    "uz": "ovqatlanish",
    "uzIPA": "ˌɑʋqætlˈænyʃ"
  },
  "menu": {
    "uz": "taomnoma",
    "uzIPA": "tˌæɑmnˈɑmæ"
  },
  "salad": {
    "uz": "salat",
    "uzIPA": "sˈælæt"
  },
  "sandwich": {
    "uz": "buterbrod",
    "uzIPA": "bʊtˈeɾbɾɑd"
  },
  "honey": {
    "uz": "asal",
    "uzIPA": "ˈæsæɫ"
  },
  "flour": {
    "uz": "un",
    "uzIPA": "ˈʊn"
  },
  "pepper": {
    "uz": "qalampir",
    "uzIPA": "qælˈæmpyɾ"
  },
  "cucumber": {
    "uz": "bodring",
    "uzIPA": "bˈɑdɾyŋ"
  },
  "cabbage": {
    "uz": "karam",
    "uzIPA": "kˈæɾæm"
  },
  "grape": {
    "uz": "uzum donasi",
    "uzIPA": "ˈʊzʊm dɑnˈæsy"
  },
  "pear": {
    "uz": "nok",
    "uzIPA": "nˈɑk"
  },
  "peach": {
    "uz": "shaftoli",
    "uzIPA": "ʃæftˈɑɫy"
  },
  "cherry": {
    "uz": "olcha",
    "uzIPA": "ˈɑɫtSæ"
  },
  "strawberry": {
    "uz": "qulupnay",
    "uzIPA": "qʊɫˈʊpnæj"
  },
  "watermelon": {
    "uz": "tarvuz",
    "uzIPA": "tˈæɾʋʊz"
  },
  "pumpkin": {
    "uz": "qovoq",
    "uzIPA": "qˈɑʋɑq"
  },
  "mushroom": {
    "uz": "qo‘ziqorin",
    "uzIPA": "qˌozyqˈɑɾyn"
  },
  "nut": {
    "uz": "yong‘oq",
    "uzIPA": "jˈɑŋʔɑq"
  },
  "bean": {
    "uz": "loviya",
    "uzIPA": "ɫɑʋˈyjæ"
  },
  "pea": {
    "uz": "no‘xat donasi",
    "uzIPA": "nˈoχæt dɑnˈæsy"
  },
  "corn": {
    "uz": "makkajo‘xori",
    "uzIPA": "mˌækkædʒoχˈɑɾy"
  },
  "yogurt": {
    "uz": "yogurt",
    "uzIPA": "jˈɑɡʊɾt"
  },
  "cream": {
    "uz": "qaymoq",
    "uzIPA": "qˈæjmɑq"
  },
  "chocolate": {
    "uz": "shokolad",
    "uzIPA": "ʃɑkˈɑlæd"
  },
  "cookie": {
    "uz": "pechenye",
    "uzIPA": "petSˈenje"
  },
  "sausage": {
    "uz": "kolbasa",
    "uzIPA": "kɑɫbˈæsæ"
  },
  "beef": {
    "uz": "mol go‘shti",
    "uzIPA": "mˈɑɫ ɡˈoʃty"
  },
  "pork": {
    "uz": "cho‘chqa go‘shti",
    "uzIPA": "tSˈotSqæ ɡˈoʃty"
  },
  "lamb": {
    "uz": "qo‘zichoq",
    "uzIPA": "qozˈytSɑq"
  },
  "seafood": {
    "uz": "dengiz mahsulotlari",
    "uzIPA": "dˈeŋyz mˌæhsʊɫɑtlˈæɾy"
  },
  "lemonade": {
    "uz": "limonad",
    "uzIPA": "ɫymˈɑnæd"
  },
  "clothes": {
    "uz": "kiyim",
    "uzIPA": "kˈyjym"
  },
  "dress": {
    "uz": "ayollar ko‘ylagi",
    "uzIPA": "æjˈɑɫlæɾ kojlˈæɡy"
  },
  "skirt": {
    "uz": "yubka",
    "uzIPA": "jˈʊbkæ"
  },
  "trousers": {
    "uz": "shim",
    "uzIPA": "ʃˈym"
  },
  "jacket": {
    "uz": "kurtka",
    "uzIPA": "kˈʊɾtkæ"
  },
  "sweater": {
    "uz": "sviter",
    "uzIPA": "sʋˈyteɾ"
  },
  "glove": {
    "uz": "qo‘lqop",
    "uzIPA": "qˈoɫqɑp"
  },
  "scarf": {
    "uz": "sharf",
    "uzIPA": "ʃˈæɾf"
  },
  "belt": {
    "uz": "kamar",
    "uzIPA": "kˈæmæɾ"
  },
  "pocket": {
    "uz": "cho‘ntak",
    "uzIPA": "tSˈontæk"
  },
  "button": {
    "uz": "tugma",
    "uzIPA": "tˈʊɡmæ"
  },
  "umbrella": {
    "uz": "soyabon",
    "uzIPA": "sɑjˈæbɑn"
  },
  "glasses": {
    "uz": "ko‘zoynak",
    "uzIPA": "kozˈɑjnæk"
  },
  "ring": {
    "uz": "uzuk",
    "uzIPA": "ˈʊzʊk"
  },
  "necklace": {
    "uz": "marjon",
    "uzIPA": "mˈæɾdʒɑn"
  },
  "lesson": {
    "uz": "dars",
    "uzIPA": "dˈæɾs"
  },
  "subject": {
    "uz": "o‘quv fani",
    "uzIPA": "ˈoqʊʋ fˌæny"
  },
  "homework": {
    "uz": "uy vazifasi",
    "uzIPA": "ˈʊj ʋˌæzyfˌæsy"
  },
  "exam": {
    "uz": "imtihon",
    "uzIPA": "ymtˈyhɑn"
  },
  "grade": {
    "uz": "o‘qish bahosi",
    "uzIPA": "ˈoqyʃ bæhˈɑsy"
  },
  "notebook": {
    "uz": "daftar",
    "uzIPA": "dˈæftˌæɾ"
  },
  "dictionary": {
    "uz": "lug‘at",
    "uzIPA": "ɫˈʊʁæt"
  },
  "language": {
    "uz": "til",
    "uzIPA": "tˈyɫ"
  },
  "sentence": {
    "uz": "gap",
    "uzIPA": "ɡˈæp"
  },
  "letter": {
    "uz": "harf",
    "uzIPA": "hˈæɾf"
  },
  "word": {
    "uz": "so‘z",
    "uzIPA": "sˈoz"
  },
  "question": {
    "uz": "savol",
    "uzIPA": "sˈæʋɑɫ"
  },
  "example": {
    "uz": "misol",
    "uzIPA": "mˈysɑɫ"
  },
  "mistake": {
    "uz": "xato",
    "uzIPA": "χˈætɑ"
  },
  "rule": {
    "uz": "qoida",
    "uzIPA": "qɑˈydæ"
  },
  "exercise": {
    "uz": "mashq",
    "uzIPA": "mˈæʃq"
  },
  "practice": {
    "uz": "amaliyot",
    "uzIPA": "ˌæmæɫˈyjɑt"
  },
  "skill": {
    "uz": "ko‘nikma",
    "uzIPA": "konˈykmæ"
  },
  "knowledge": {
    "uz": "bilim",
    "uzIPA": "bˈyɫym"
  },
  "education": {
    "uz": "ta’lim",
    "uzIPA": "tˈæʔɫym"
  },
  "university": {
    "uz": "universitet",
    "uzIPA": "ˌʊnyʋeɾsˈytet"
  },
  "library": {
    "uz": "kutubxona",
    "uzIPA": "kˌʊtʊbχˈɑnæ"
  },
  "history": {
    "uz": "tarix",
    "uzIPA": "tˈæɾyχ"
  },
  "geography": {
    "uz": "geografiya",
    "uzIPA": "ɡˈeɑɡɾæfˌyjæ"
  },
  "science": {
    "uz": "fan",
    "uzIPA": "fˈæn"
  },
  "mathematics": {
    "uz": "matematika",
    "uzIPA": "mˌætemætˈykæ"
  },
  "art": {
    "uz": "san’at",
    "uzIPA": "sˈænʔæt"
  },
  "music": {
    "uz": "musiqa",
    "uzIPA": "mʊsˈyqæ"
  },
  "sport": {
    "uz": "sport",
    "uzIPA": "spˈɑɾt"
  },
  "team": {
    "uz": "jamoa",
    "uzIPA": "dʒæmˈɑæ"
  },
  "player": {
    "uz": "o‘yinchi",
    "uzIPA": "ojˈyntSy"
  },
  "coach": {
    "uz": "murabbiy",
    "uzIPA": "mʊɾˈæbbyj"
  },
  "race": {
    "uz": "poyga",
    "uzIPA": "pˈɑjɡæ"
  },
  "match": {
    "uz": "sport uchrashuvi",
    "uzIPA": "spˈɑɾt ˌʊtSɾæʃˈʊʋy"
  },
  "goal": {
    "uz": "maqsad",
    "uzIPA": "mˈæqsæd"
  },
  "score": {
    "uz": "o‘yin hisobi",
    "uzIPA": "ˈojyn hysˈɑby"
  },
  "winner": {
    "uz": "g‘olib",
    "uzIPA": "ʁˈɑɫyb"
  },
  "prize": {
    "uz": "sovrin",
    "uzIPA": "sˈɑʋɾyn"
  },
  "competition": {
    "uz": "musobaqa",
    "uzIPA": "mˌʊsɑbˈæqæ"
  },
  "training": {
    "uz": "mashg‘ulot",
    "uzIPA": "mæʃʁˈʊɫɑt"
  },
  "pool": {
    "uz": "basseyn",
    "uzIPA": "bˈæssejn"
  },
  "stadium": {
    "uz": "stadion",
    "uzIPA": "stædˈyɑn"
  },
  "cinema": {
    "uz": "kinoteatr",
    "uzIPA": "kˌynɑtˈeætɾ"
  },
  "theater": {
    "uz": "teatr",
    "uzIPA": "tˈeætɾ"
  },
  "museum": {
    "uz": "muzey",
    "uzIPA": "mˈʊzej"
  },
  "concert": {
    "uz": "konsert",
    "uzIPA": "kˈɑnseɾt"
  },
  "festival": {
    "uz": "festival",
    "uzIPA": "fˌestˈyʋæɫ"
  },
  "painting": {
    "uz": "surat",
    "uzIPA": "sˈʊɾæt"
  },
  "photo": {
    "uz": "fotosurat",
    "uzIPA": "fˌɑtɑsˈʊɾæt"
  },
  "camera": {
    "uz": "fotoapparat",
    "uzIPA": "fˌɑtɑæppˈæɾæt"
  },
  "newspaper": {
    "uz": "gazeta",
    "uzIPA": "ɡæzˈetæ"
  },
  "magazine": {
    "uz": "jurnal",
    "uzIPA": "dʒˈʊɾnæɫ"
  },
  "story": {
    "uz": "hikoya",
    "uzIPA": "hykˈɑjæ"
  },
  "novel": {
    "uz": "roman",
    "uzIPA": "ɾˈɑmæn"
  },
  "poem": {
    "uz": "she’r",
    "uzIPA": "ʃˈeʔɾ"
  },
  "song": {
    "uz": "qo‘shiq",
    "uzIPA": "qˈoʃyq"
  },
  "movie": {
    "uz": "film",
    "uzIPA": "fˈyɫm"
  },
  "game": {
    "uz": "o‘yin",
    "uzIPA": "ˈojyn"
  },
  "hobby": {
    "uz": "sevimli mashg‘ulot",
    "uzIPA": "seʋˈymɫy mæʃʁˈʊɫɑt"
  },
  "collection": {
    "uz": "to‘plam",
    "uzIPA": "tˈoplæm"
  },
  "computer": {
    "uz": "kompyuter",
    "uzIPA": "kɑmpjˈʊteɾ"
  },
  "screen": {
    "uz": "ekran",
    "uzIPA": "ˈekɾæn"
  },
  "keyboard": {
    "uz": "klaviatura",
    "uzIPA": "klˌæʋyætˈʊɾæ"
  },
  "printer": {
    "uz": "printer",
    "uzIPA": "pɾˈynteɾ"
  },
  "speaker": {
    "uz": "karnay",
    "uzIPA": "kˈæɾnæj"
  },
  "battery": {
    "uz": "batareya",
    "uzIPA": "bˌætæɾˈejæ"
  },
  "charger": {
    "uz": "quvvatlagich",
    "uzIPA": "qˌʊʋʋætlˈæɡytS"
  },
  "cable": {
    "uz": "kabel",
    "uzIPA": "kˈæbeɫ"
  },
  "message": {
    "uz": "xabar",
    "uzIPA": "χˈæbæɾ"
  },
  "email": {
    "uz": "elektron xat",
    "uzIPA": "elˈektɾɑn χˈæt"
  },
  "website": {
    "uz": "veb-sayt",
    "uzIPA": "ʋˈebsˈæjt"
  },
  "password": {
    "uz": "parol",
    "uzIPA": "pˈæɾɑɫ"
  },
  "file": {
    "uz": "fayl",
    "uzIPA": "fˈæjɫ"
  },
  "folder": {
    "uz": "papka",
    "uzIPA": "pˈæpkæ"
  },
  "program": {
    "uz": "dastur",
    "uzIPA": "dˈæstʊɾ"
  },
  "network": {
    "uz": "tarmoq",
    "uzIPA": "tˈæɾmɑq"
  },
  "internet": {
    "uz": "internet",
    "uzIPA": "yntˈeɾnet"
  },
  "search": {
    "uz": "qidiruv",
    "uzIPA": "qydˈyɾʊʋ"
  },
  "news": {
    "uz": "yangiliklar",
    "uzIPA": "jˌæŋyɫˈyklæɾ"
  },
  "advertisement": {
    "uz": "reklama",
    "uzIPA": "ɾeklˈæmæ"
  },
  "meeting": {
    "uz": "uchrashuv",
    "uzIPA": "ʊtSɾˈæʃʊʋ"
  },
  "appointment": {
    "uz": "qabulga yozilish",
    "uzIPA": "qæbˈʊɫɡæ jɑzˈyɫyʃ"
  },
  "office": {
    "uz": "ofis",
    "uzIPA": "ˈɑfˌys"
  },
  "company": {
    "uz": "kompaniya",
    "uzIPA": "kˌɑmpænˈyjæ"
  },
  "business": {
    "uz": "biznes",
    "uzIPA": "bˈyznes"
  },
  "job": {
    "uz": "yollanma ish",
    "uzIPA": "jɑɫlˈænmæ ˈyʃ"
  },
  "career": {
    "uz": "karyera",
    "uzIPA": "kæɾjˈeɾæ"
  },
  "salary": {
    "uz": "ish haqi",
    "uzIPA": "ˈyʃ hˈæqy"
  },
  "project": {
    "uz": "loyiha",
    "uzIPA": "ɫɑjˈyhæ"
  },
  "plan": {
    "uz": "reja",
    "uzIPA": "ɾˈedʒæ"
  },
  "report": {
    "uz": "hisobot",
    "uzIPA": "hysˈɑbɑt"
  },
  "schedule": {
    "uz": "jadval",
    "uzIPA": "dʒˈædʋæɫ"
  },
  "deadline": {
    "uz": "oxirgi muddat",
    "uzIPA": "ɑχˈyɾɡy mˈʊddæt"
  },
  "task": {
    "uz": "vazifa",
    "uzIPA": "ʋæzˈyfˌæ"
  },
  "result": {
    "uz": "natija",
    "uzIPA": "nætˈydʒæ"
  },
  "success": {
    "uz": "muvaffaqiyat",
    "uzIPA": "mˌʊʋæffˌæqˈyjæt"
  },
  "failure": {
    "uz": "muvaffaqiyatsizlik",
    "uzIPA": "mˌʊʋæffˌæqyjætsˈyzɫyk"
  },
  "problem": {
    "uz": "muammo",
    "uzIPA": "mʊˈæmmɑ"
  },
  "solution": {
    "uz": "muammo yechimi",
    "uzIPA": "mʊˈæmmɑ jetSˈymy"
  },
  "advice": {
    "uz": "maslahat",
    "uzIPA": "mæslˈæhæt"
  },
  "accept": {
    "uz": "qabul qilmoq",
    "uzIPA": "qˈæbʊɫ qˈyɫmɑq"
  },
  "refuse": {
    "uz": "rad etmoq",
    "uzIPA": "ɾˈæd ˈetmɑq"
  },
  "agree": {
    "uz": "rozi bo‘lmoq",
    "uzIPA": "ɾˈɑzy bˈoɫmɑq"
  },
  "disagree": {
    "uz": "rozi bo‘lmaslik",
    "uzIPA": "ɾˈɑzy boɫmˈæsɫyk"
  },
  "decide": {
    "uz": "qaror qilmoq",
    "uzIPA": "qˈæɾɑɾ qˈyɫmɑq"
  },
  "explain": {
    "uz": "tushuntirmoq",
    "uzIPA": "tˌʊʃʊntˈyɾmɑq"
  },
  "describe": {
    "uz": "tasvirlamoq",
    "uzIPA": "tˌæsʋyɾlˈæmɑq"
  },
  "compare": {
    "uz": "taqqoslamoq",
    "uzIPA": "tˌæqqɑslˈæmɑq"
  },
  "improve": {
    "uz": "yaxshilamoq",
    "uzIPA": "jˌæχʃylˈæmɑq"
  },
  "develop": {
    "uz": "rivojlantirmoq",
    "uzIPA": "ɾˌyʋɑdʒlæntˈyɾmɑq"
  },
  "prepare": {
    "uz": "tayyorlamoq",
    "uzIPA": "tˌæjjɑɾlˈæmɑq"
  },
  "organize": {
    "uz": "tashkil qilmoq",
    "uzIPA": "tˈæʃkyɫ qˈyɫmɑq"
  },
  "manage": {
    "uz": "boshqarmoq",
    "uzIPA": "bɑʃqˈæɾmɑq"
  },
  "suggest": {
    "uz": "taklif qilmoq",
    "uzIPA": "tˈækɫyf qˈyɫmɑq"
  },
  "recommend": {
    "uz": "tavsiya qilmoq",
    "uzIPA": "tæʋsˈyjæ qˈyɫmɑq"
  },
  "invite": {
    "uz": "taklif etmoq",
    "uzIPA": "tˈækɫyf ˈetmɑq"
  },
  "promise": {
    "uz": "va’da bermoq",
    "uzIPA": "ʋˈæʔdæ bˈeɾmɑq"
  },
  "apologize": {
    "uz": "uzr so‘ramoq",
    "uzIPA": "ˈʊzɾ soɾˈæmɑq"
  },
  "thank": {
    "uz": "minnatdorchilik bildirmoq",
    "uzIPA": "mˌynnætdɑɾtSˈyɫyk byɫdˈyɾmɑq"
  },
  "welcome": {
    "uz": "xush kelibsiz demoq",
    "uzIPA": "χˈʊʃ keɫˈybsyz dˈemɑq"
  },
  "celebrate": {
    "uz": "nishonlamoq",
    "uzIPA": "nˌyʃɑnlˈæmɑq"
  },
  "enjoy": {
    "uz": "zavqlanmoq",
    "uzIPA": "zæʋqlˈænmɑq"
  },
  "prefer": {
    "uz": "afzal ko‘rmoq",
    "uzIPA": "ˈæfzˌæɫ kˈoɾmɑq"
  },
  "imagine": {
    "uz": "tasavvur qilmoq",
    "uzIPA": "tæsˈæʋʋʊɾ qˈyɫmɑq"
  },
  "notice": {
    "uz": "payqamoq",
    "uzIPA": "pæjqˈæmɑq"
  },
  "recognize": {
    "uz": "tanimoq",
    "uzIPA": "tænˈymɑq"
  },
  "realize": {
    "uz": "anglab yetmoq",
    "uzIPA": "ˈæŋlæb jˈetmɑq"
  },
  "discover": {
    "uz": "kashf qilmoq",
    "uzIPA": "kˈæʃf qˈyɫmɑq"
  },
  "invent": {
    "uz": "ixtiro qilmoq",
    "uzIPA": "yχtˈyɾɑ qˈyɫmɑq"
  },
  "create": {
    "uz": "yaratmoq",
    "uzIPA": "jæɾˈætmɑq"
  },
  "produce": {
    "uz": "ishlab chiqarmoq",
    "uzIPA": "ˈyʃlæb tSyqˈæɾmɑq"
  },
  "provide": {
    "uz": "ta’minlamoq",
    "uzIPA": "tˌæʔmynlˈæmɑq"
  },
  "receive": {
    "uz": "qabul qilib olmoq",
    "uzIPA": "qˈæbʊɫ qˈyɫyb ˈɑɫmɑq"
  },
  "collect": {
    "uz": "yig‘moq",
    "uzIPA": "jˈyʁmɑq"
  },
  "save": {
    "uz": "tejamoq",
    "uzIPA": "tedʒˈæmɑq"
  },
  "spend": {
    "uz": "sarflamoq",
    "uzIPA": "sæɾflˈæmɑq"
  },
  "borrow": {
    "uz": "qarz olmoq",
    "uzIPA": "qˈæɾz ˈɑɫmɑq"
  },
  "lend": {
    "uz": "qarz bermoq",
    "uzIPA": "qˈæɾz bˈeɾmɑq"
  },
  "owe": {
    "uz": "qarzdor bo‘lmoq",
    "uzIPA": "qˈæɾzdɑɾ bˈoɫmɑq"
  },
  "afford": {
    "uz": "qurbi yetmoq",
    "uzIPA": "qˈʊɾby jˈetmɑq"
  },
  "order": {
    "uz": "buyurtma bermoq",
    "uzIPA": "bʊjˈʊɾtmæ bˈeɾmɑq"
  },
  "deliver": {
    "uz": "yetkazib bermoq",
    "uzIPA": "jetkˈæzyb bˈeɾmɑq"
  },
  "pack": {
    "uz": "qadoqlamoq",
    "uzIPA": "qˌædɑqlˈæmɑq"
  },
  "unpack": {
    "uz": "o‘ramdan chiqarmoq",
    "uzIPA": "oɾˈæmdæn tSyqˈæɾmɑq"
  },
  "rent": {
    "uz": "ijaraga olmoq",
    "uzIPA": "ˌydʒæɾˈæɡæ ˈɑɫmɑq"
  },
  "booklet": {
    "uz": "risola",
    "uzIPA": "ɾysˈɑlæ"
  },
  "cancel": {
    "uz": "bekor qilmoq",
    "uzIPA": "bˈekɑɾ qˈyɫmɑq"
  },
  "check": {
    "uz": "tekshirmoq",
    "uzIPA": "tekʃˈyɾmɑq"
  },
  "confirm": {
    "uz": "tasdiqlamoq",
    "uzIPA": "tˌæsdyqlˈæmɑq"
  },
  "sign": {
    "uz": "imzolamoq",
    "uzIPA": "ˌymzɑlˈæmɑq"
  },
  "include": {
    "uz": "tarkibga kiritmoq",
    "uzIPA": "tæɾkˈybɡæ kyɾˈytmɑq"
  },
  "contain": {
    "uz": "o‘z ichiga olmoq",
    "uzIPA": "ˈoz ytSˌyɡæ ˈɑɫmɑq"
  },
  "belong": {
    "uz": "tegishli bo‘lmoq",
    "uzIPA": "teɡˈyʃɫy bˈoɫmɑq"
  },
  "depend": {
    "uz": "bog‘liq bo‘lmoq",
    "uzIPA": "bˈɑʁɫyq bˈoɫmɑq"
  },
  "happen": {
    "uz": "sodir bo‘lmoq",
    "uzIPA": "sˈɑdyɾ bˈoɫmɑq"
  },
  "seem": {
    "uz": "tuyulmoq",
    "uzIPA": "tʊjˈʊɫmɑq"
  },
  "appear": {
    "uz": "paydo bo‘lmoq",
    "uzIPA": "pˈæjdɑ bˈoɫmɑq"
  },
  "disappear": {
    "uz": "g‘oyib bo‘lmoq",
    "uzIPA": "ʁˈɑjyb bˈoɫmɑq"
  },
  "continue": {
    "uz": "davom ettirmoq",
    "uzIPA": "dˈæʋɑm ettˈyɾmɑq"
  },
  "complete": {
    "uz": "yakunlamoq",
    "uzIPA": "jˌækʊnlˈæmɑq"
  },
  "repeat": {
    "uz": "takrorlamoq",
    "uzIPA": "tˌækɾɑɾlˈæmɑq"
  },
  "replace": {
    "uz": "almashtirmoq",
    "uzIPA": "ˌæɫmæʃtˈyɾmɑq"
  },
  "remove": {
    "uz": "olib tashlamoq",
    "uzIPA": "ˈɑɫyb tæʃlˈæmɑq"
  },
  "add": {
    "uz": "qo‘shmoq",
    "uzIPA": "qˈoʃmɑq"
  },
  "reduce": {
    "uz": "kamaytirmoq",
    "uzIPA": "kˌæmæjtˈyɾmɑq"
  },
  "increase": {
    "uz": "ko‘paytirmoq",
    "uzIPA": "kˌopæjtˈyɾmɑq"
  },
  "raise": {
    "uz": "ko‘tarmoq",
    "uzIPA": "kotˈæɾmɑq"
  },
  "lower": {
    "uz": "tushirmoq",
    "uzIPA": "tʊʃˈyɾmɑq"
  },
  "reach": {
    "uz": "erishmoq",
    "uzIPA": "eɾˈyʃmɑq"
  },
  "follow": {
    "uz": "ergashmoq",
    "uzIPA": "eɾɡˈæʃmɑq"
  },
  "lead": {
    "uz": "yetakchilik qilmoq",
    "uzIPA": "jˌetæktSˈyɫyk qˈyɫmɑq"
  },
  "join": {
    "uz": "qo‘shilmoq",
    "uzIPA": "qoʃˈyɫmɑq"
  },
  "separate": {
    "uz": "ajratmoq",
    "uzIPA": "ædʒɾˈætmɑq"
  },
  "connect": {
    "uz": "ulamoq",
    "uzIPA": "ʊlˈæmɑq"
  },
  "cover": {
    "uz": "qoplamoq",
    "uzIPA": "qɑplˈæmɑq"
  },
  "protect": {
    "uz": "himoya qilmoq",
    "uzIPA": "hymˈɑjæ qˈyɫmɑq"
  },
  "prevent": {
    "uz": "oldini olmoq",
    "uzIPA": "ɑɫdˈyny ˈɑɫmɑq"
  },
  "avoid": {
    "uz": "chetlab o‘tmoq",
    "uzIPA": "tSˈetlæb ˈotmɑq"
  },
  "allow": {
    "uz": "ruxsat bermoq",
    "uzIPA": "ɾˈʊχsæt bˈeɾmɑq"
  },
  "forbid": {
    "uz": "taqiqlamoq",
    "uzIPA": "tˌæqyqlˈæmɑq"
  },
  "require": {
    "uz": "talab qilmoq",
    "uzIPA": "tˈælæb qˈyɫmɑq"
  },
  "support": {
    "uz": "qo‘llab-quvvatlamoq",
    "uzIPA": "qˈoɫlæbqˌʊʋʋætlˈæmɑq"
  },
  "encourage": {
    "uz": "ruhlantirmoq",
    "uzIPA": "ɾˌʊhlæntˈyɾmɑq"
  },
  "worry": {
    "uz": "xavotirlanmoq",
    "uzIPA": "χˌæʋɑtyɾlˈænmɑq"
  },
  "relax": {
    "uz": "bo‘shashmoq",
    "uzIPA": "boʃˈæʃmɑq"
  },
  "rest": {
    "uz": "dam olmoq",
    "uzIPA": "dˈæm ˈɑɫmɑq"
  },
  "breathe": {
    "uz": "nafas olmoq",
    "uzIPA": "nˈæfˌæs ˈɑɫmɑq"
  },
  "hurt": {
    "uz": "og‘ritmoq",
    "uzIPA": "ɑʁɾˈytmɑq"
  },
  "heal": {
    "uz": "bitmoq",
    "uzIPA": "bˈytmɑq"
  },
  "recover": {
    "uz": "sog‘aymoq",
    "uzIPA": "sɑʁˈæjmɑq"
  },
  "survive": {
    "uz": "omon qolmoq",
    "uzIPA": "ˈɑmɑn qˈɑɫmɑq"
  },
  "escape": {
    "uz": "qochmoq",
    "uzIPA": "qˈɑtSmɑq"
  },
  "hide": {
    "uz": "yashirmoq",
    "uzIPA": "jæʃˈyɾmɑq"
  },
  "seek": {
    "uz": "qidirmoq",
    "uzIPA": "qydˈyɾmɑq"
  },
  "chase": {
    "uz": "quvmoq",
    "uzIPA": "qˈʊʋmɑq"
  },
  "fight": {
    "uz": "jang qilmoq",
    "uzIPA": "dʒˈæŋ qˈyɫmɑq"
  },
  "win": {
    "uz": "g‘alaba qozonmoq",
    "uzIPA": "ʁælˈæbæ qɑzˈɑnmɑq"
  },
  "defeat": {
    "uz": "raqibni yengmoq",
    "uzIPA": "ɾæqˈybny jˈeŋmɑq"
  },
  "fail": {
    "uz": "muvaffaqiyatsizlikka uchramoq",
    "uzIPA": "mˌʊʋæffˌæqyjˌætsyzɫˈykkæ ʊtSɾˈæmɑq"
  },
  "succeed": {
    "uz": "muvaffaqiyatga erishmoq",
    "uzIPA": "mˌʊʋæffˌæqyjˈætɡæ eɾˈyʃmɑq"
  },
  "important": {
    "uz": "muhim",
    "uzIPA": "mˈʊhym"
  },
  "necessary": {
    "uz": "zarur",
    "uzIPA": "zˈæɾʊɾ"
  },
  "possible": {
    "uz": "mumkin",
    "uzIPA": "mˈʊmkyn"
  },
  "impossible": {
    "uz": "imkonsiz",
    "uzIPA": "ymkˈɑnsyz"
  },
  "simple": {
    "uz": "oddiy",
    "uzIPA": "ˈɑddyj"
  },
  "complicated": {
    "uz": "murakkab",
    "uzIPA": "mʊɾˈækkæb"
  },
  "useful": {
    "uz": "foydali",
    "uzIPA": "fˌɑjdˈæɫy"
  },
  "useless": {
    "uz": "foydasiz",
    "uzIPA": "fˌɑjdˈæsyz"
  },
  "careful": {
    "uz": "ehtiyotkor",
    "uzIPA": "ˌehtyjˈɑtkɑɾ"
  },
  "careless": {
    "uz": "beparvo",
    "uzIPA": "bepˈæɾʋɑ"
  },
  "polite": {
    "uz": "odobli",
    "uzIPA": "ɑdˈɑbɫy"
  },
  "rude": {
    "uz": "qo‘pol",
    "uzIPA": "qˈopɑɫ"
  },
  "honest": {
    "uz": "halol",
    "uzIPA": "hˈæɫɑɫ"
  },
  "brave": {
    "uz": "jasur",
    "uzIPA": "dʒˈæsʊɾ"
  },
  "clever": {
    "uz": "ziyrak",
    "uzIPA": "zˈyjɾæk"
  },
  "wise": {
    "uz": "dono",
    "uzIPA": "dˈɑnɑ"
  },
  "foolish": {
    "uz": "ahmoq",
    "uzIPA": "ˈæhmɑq"
  },
  "lazy": {
    "uz": "dangasa",
    "uzIPA": "dæŋˈæsæ"
  },
  "active": {
    "uz": "faol",
    "uzIPA": "fˈæɑɫ"
  },
  "creative": {
    "uz": "ijodiy",
    "uzIPA": "ydʒˈɑdyj"
  },
  "curious": {
    "uz": "qiziquvchan",
    "uzIPA": "qˌyzyqˈʊʋtSæn"
  },
  "serious": {
    "uz": "jiddiy",
    "uzIPA": "dʒˈyddyj"
  },
  "funny": {
    "uz": "kulgili",
    "uzIPA": "kʊɫɡˈyɫy"
  },
  "friendly": {
    "uz": "do‘stona",
    "uzIPA": "dostˈɑnæ"
  },
  "lonely": {
    "uz": "yolg‘iz",
    "uzIPA": "jˈɑɫʁyz"
  },
  "proud": {
    "uz": "mag‘rur",
    "uzIPA": "mˈæʁɾʊɾ"
  },
  "ashamed": {
    "uz": "uyalgan",
    "uzIPA": "ʊjˈæɫɡæn"
  },
  "surprised": {
    "uz": "hayron",
    "uzIPA": "hˈæjɾɑn"
  },
  "excited": {
    "uz": "hayajonlangan",
    "uzIPA": "hˌæjædʒɑnlˈæŋæn"
  },
  "bored": {
    "uz": "zerikkan",
    "uzIPA": "zeɾˈykkæn"
  },
  "confused": {
    "uz": "dovdiragan",
    "uzIPA": "dˌɑʋdyɾˈæɡæn"
  },
  "confident": {
    "uz": "o‘ziga ishongan",
    "uzIPA": "ozˈyɡæ yʃˈɑŋæn"
  },
  "nervous": {
    "uz": "asabiylashgan",
    "uzIPA": "ˌæsæbyjlˈæʃɡæn"
  },
  "calm": {
    "uz": "xotirjam",
    "uzIPA": "χɑtˈyɾdʒæm"
  },
  "generous": {
    "uz": "saxiy",
    "uzIPA": "sˈæχyj"
  },
  "selfish": {
    "uz": "xudbin",
    "uzIPA": "χˈʊdbyn"
  },
  "jealous": {
    "uz": "rashkchi",
    "uzIPA": "ɾˈæʃktSy"
  },
  "fair": {
    "uz": "adolatli",
    "uzIPA": "ˌædɑlˈætɫy"
  },
  "unfair": {
    "uz": "adolatsiz",
    "uzIPA": "ˌædɑlˈætsyz"
  },
  "patiently": {
    "uz": "sabr bilan",
    "uzIPA": "sˈæbɾ bˌylæn"
  },
  "reliable": {
    "uz": "ishonchli",
    "uzIPA": "yʃˈɑntSɫy"
  },
  "responsible": {
    "uz": "mas’uliyatli",
    "uzIPA": "mˌæsʔʊɫyjˈætɫy"
  },
  "independent": {
    "uz": "mustaqil",
    "uzIPA": "mʊstˈæqyɫ"
  },
  "popular": {
    "uz": "ommabop",
    "uzIPA": "ɑmmˈæbɑp"
  },
  "famous": {
    "uz": "mashhur",
    "uzIPA": "mˈæʃhʊɾ"
  },
  "ordinary": {
    "uz": "odatiy",
    "uzIPA": "ɑdˈætyj"
  },
  "special": {
    "uz": "maxsus",
    "uzIPA": "mˈæχsʊs"
  },
  "unique": {
    "uz": "noyob",
    "uzIPA": "nˈɑjɑb"
  },
  "strange": {
    "uz": "g‘alati",
    "uzIPA": "ʁælˈæty"
  },
  "familiar": {
    "uz": "tanish",
    "uzIPA": "tˈænyʃ"
  },
  "foreign": {
    "uz": "xorijiy",
    "uzIPA": "χɑɾˈydʒyj"
  },
  "local": {
    "uz": "mahalliy",
    "uzIPA": "mæhˈæɫɫyj"
  },
  "public": {
    "uz": "jamoatga oid",
    "uzIPA": "dʒˌæmɑˈætɡæ ˈɑyd"
  },
  "private": {
    "uz": "xususiy",
    "uzIPA": "χʊsˈʊsyj"
  },
  "modern": {
    "uz": "zamonaviy",
    "uzIPA": "zˌæmɑnˈæʋyj"
  },
  "ancient": {
    "uz": "qadimiy",
    "uzIPA": "qædˈymyj"
  },
  "traditional": {
    "uz": "an’anaviy",
    "uzIPA": "ˌænʔænˈæʋyj"
  },
  "natural": {
    "uz": "tabiiy",
    "uzIPA": "tæbˈyyj"
  },
  "artificial": {
    "uz": "sun’iy",
    "uzIPA": "sˈʊnʔyj"
  },
  "physical": {
    "uz": "jismoniy",
    "uzIPA": "dʒysmˈɑnyj"
  },
  "mental": {
    "uz": "aqliy",
    "uzIPA": "ˈæqɫyj"
  },
  "social": {
    "uz": "ijtimoiy",
    "uzIPA": "ˌydʒtymˈɑyj"
  },
  "personal": {
    "uz": "shaxsiy",
    "uzIPA": "ʃˈæχsyj"
  },
  "professional": {
    "uz": "kasbiy",
    "uzIPA": "kˈæsbyj"
  },
  "comfortable": {
    "uz": "qulay",
    "uzIPA": "qˈʊlæj"
  },
  "convenient": {
    "uz": "qulaylik jihatidan mos",
    "uzIPA": "qʊlˈæjɫyk dʒˌyhætˈydæn mˈɑs"
  },
  "affordable": {
    "uz": "hamyonbop",
    "uzIPA": "hæmjˈɑnbɑp"
  },
  "expensive": {
    "uz": "qimmat",
    "uzIPA": "qˈymmæt"
  },
  "cheap": {
    "uz": "arzon",
    "uzIPA": "ˈæɾzɑn"
  },
  "valuable": {
    "uz": "qadrli",
    "uzIPA": "qˈædɾɫy"
  },
  "worthless": {
    "uz": "qadrsiz",
    "uzIPA": "qˈædɾsyz"
  },
  "correct": {
    "uz": "to‘g‘ri",
    "uzIPA": "tˈoʁɾy"
  },
  "wrong": {
    "uz": "noto‘g‘ri",
    "uzIPA": "nɑtˈoʁɾy"
  },
  "accurate": {
    "uz": "aniq",
    "uzIPA": "ˈænyq"
  },
  "rough": {
    "uz": "g‘adir-budur",
    "uzIPA": "ʁˈædyɾbˈʊdʊɾ"
  },
  "smooth": {
    "uz": "silliq",
    "uzIPA": "sˈyɫɫyq"
  },
  "sharp": {
    "uz": "o‘tkir",
    "uzIPA": "ˈotkyɾ"
  },
  "blunt": {
    "uz": "o‘tmas",
    "uzIPA": "ˈotmæs"
  },
  "heavy": {
    "uz": "og‘ir",
    "uzIPA": "ˈɑʁyɾ"
  },
  "lightweight": {
    "uz": "yengil",
    "uzIPA": "jˈeŋyɫ"
  },
  "thick": {
    "uz": "qalin",
    "uzIPA": "qˈæɫyn"
  },
  "thin": {
    "uz": "yupqa",
    "uzIPA": "jˈʊpqæ"
  },
  "wide": {
    "uz": "keng",
    "uzIPA": "kˈeŋ"
  },
  "narrow": {
    "uz": "tor",
    "uzIPA": "tˈɑɾ"
  },
  "deep": {
    "uz": "chuqur",
    "uzIPA": "tSˈʊqʊɾ"
  },
  "shallow": {
    "uz": "sayoz",
    "uzIPA": "sˈæjɑz"
  },
  "steep": {
    "uz": "tik qiyalik",
    "uzIPA": "tˈyk qyjˈæɫyk"
  },
  "flat": {
    "uz": "yassi",
    "uzIPA": "jˈæssy"
  },
  "round": {
    "uz": "dumaloq",
    "uzIPA": "dʊmˈæɫɑq"
  },
  "square": {
    "uz": "kvadrat shaklli",
    "uzIPA": "kʋˈædɾæt ʃˈækɫɫy"
  },
  "straight": {
    "uz": "to‘g‘ri",
    "uzIPA": "tˈoʁɾy"
  },
  "curved": {
    "uz": "egilgan",
    "uzIPA": "eɡˈyɫɡæn"
  },
  "solid": {
    "uz": "qattiq",
    "uzIPA": "qˈættyq"
  },
  "liquid": {
    "uz": "suyuq",
    "uzIPA": "sˈʊjʊq"
  },
  "fresh": {
    "uz": "yangi",
    "uzIPA": "jˈæŋy"
  },
  "rotten": {
    "uz": "chirigan",
    "uzIPA": "tSyɾˈyɡæn"
  },
  "ripe": {
    "uz": "pishgan",
    "uzIPA": "pˈyʃɡæn"
  },
  "raw": {
    "uz": "xom",
    "uzIPA": "χˈɑm"
  },
  "delicious": {
    "uz": "mazali",
    "uzIPA": "mæzˈæɫy"
  },
  "bitter": {
    "uz": "achchiq",
    "uzIPA": "ˈætStSyq"
  },
  "freedom": {
    "uz": "erkinlik",
    "uzIPA": "eɾkˈynɫyk"
  },
  "justice": {
    "uz": "odil sudlov",
    "uzIPA": "ˈɑdyɫ sˈʊdɫɑʋ"
  },
  "equality": {
    "uz": "tenglik",
    "uzIPA": "tˈeŋɫyk"
  },
  "honesty": {
    "uz": "halollik",
    "uzIPA": "hæɫˈɑɫɫyk"
  },
  "courage": {
    "uz": "jasorat",
    "uzIPA": "dʒæsˈɑɾæt"
  },
  "kindness": {
    "uz": "mehribonlik",
    "uzIPA": "mˌehɾybˈɑnɫyk"
  },
  "patience": {
    "uz": "sabr",
    "uzIPA": "sˈæbɾ"
  },
  "respect": {
    "uz": "hurmat",
    "uzIPA": "hˈʊɾmæt"
  },
  "trust": {
    "uz": "ishonch",
    "uzIPA": "ˈyʃɑntS"
  },
  "loyalty": {
    "uz": "sadoqat",
    "uzIPA": "sædˈɑqæt"
  },
  "friendship": {
    "uz": "do‘stlik",
    "uzIPA": "dˈostɫyk"
  },
  "relationship": {
    "uz": "o‘zaro munosabat",
    "uzIPA": "ozˈæɾɑ mˌʊnɑsˈæbæt"
  },
  "community": {
    "uz": "hamjamiyat",
    "uzIPA": "hˌæmdʒæmˈyjæt"
  },
  "society": {
    "uz": "jamiyat",
    "uzIPA": "dʒæmˈyjæt"
  },
  "culture": {
    "uz": "madaniyat",
    "uzIPA": "mˌædænˈyjæt"
  },
  "tradition": {
    "uz": "an’ana",
    "uzIPA": "ænʔˈænæ"
  },
  "custom": {
    "uz": "urf-odat",
    "uzIPA": "ˈʊɾfˈɑdæt"
  },
  "belief": {
    "uz": "e’tiqod",
    "uzIPA": "eʔtˈyqɑd"
  },
  "religion": {
    "uz": "din",
    "uzIPA": "dˈyn"
  },
  "faith": {
    "uz": "imon",
    "uzIPA": "ˈymɑn"
  },
  "opinion": {
    "uz": "fikr",
    "uzIPA": "fˈykɾ"
  },
  "attitude": {
    "uz": "munosabat",
    "uzIPA": "mˌʊnɑsˈæbæt"
  },
  "behavior": {
    "uz": "xulq-atvor",
    "uzIPA": "χˈʊɫqˈætʋɑɾ"
  },
  "habit": {
    "uz": "odat",
    "uzIPA": "ˈɑdæt"
  },
  "character": {
    "uz": "fe’l-atvor",
    "uzIPA": "fˌeʔlˈætʋɑɾ"
  },
  "personality": {
    "uz": "shaxsiyat",
    "uzIPA": "ʃæχsˈyjæt"
  },
  "emotion": {
    "uz": "hissiyot",
    "uzIPA": "hyssˈyjɑt"
  },
  "feeling": {
    "uz": "tuyg‘u",
    "uzIPA": "tˈʊjʁʊ"
  },
  "happiness": {
    "uz": "baxt",
    "uzIPA": "bˈæχt"
  },
  "sadness": {
    "uz": "g‘am",
    "uzIPA": "ʁˈæm"
  },
  "anger": {
    "uz": "g‘azab",
    "uzIPA": "ʁˈæzæb"
  },
  "fear": {
    "uz": "qo‘rquv",
    "uzIPA": "qˈoɾqʊʋ"
  },
  "joy": {
    "uz": "quvonch",
    "uzIPA": "qˈʊʋɑntS"
  },
  "surprise": {
    "uz": "kutilmagan hodisa",
    "uzIPA": "kˌʊtyɫmˈæɡæn hɑdˈysæ"
  },
  "shame": {
    "uz": "uyat",
    "uzIPA": "ˈʊjæt"
  },
  "guilt": {
    "uz": "ayb",
    "uzIPA": "ˈæjb"
  },
  "pride": {
    "uz": "faxr",
    "uzIPA": "fˈæχɾ"
  },
  "envy": {
    "uz": "hasad",
    "uzIPA": "hˈæsæd"
  },
  "confidence": {
    "uz": "o‘ziga ishonch",
    "uzIPA": "ozˈyɡæ ˈyʃɑntS"
  },
  "anxiety": {
    "uz": "tashvish",
    "uzIPA": "tˈæʃʋyʃ"
  },
  "stress": {
    "uz": "stress",
    "uzIPA": "stɾˈess"
  },
  "peace": {
    "uz": "tinchlik",
    "uzIPA": "tˈyntSɫyk"
  },
  "war": {
    "uz": "urush",
    "uzIPA": "ˈʊɾʊʃ"
  },
  "conflict": {
    "uz": "nizo",
    "uzIPA": "nˈyzɑ"
  },
  "agreement": {
    "uz": "kelishuv",
    "uzIPA": "keɫˈyʃʊʋ"
  },
  "argument": {
    "uz": "bahs",
    "uzIPA": "bˈæhs"
  },
  "reason": {
    "uz": "sabab",
    "uzIPA": "sˈæbæb"
  },
  "purpose": {
    "uz": "vazifa va maqsad",
    "uzIPA": "ʋæzˈyfˌæ ʋˈæ mˈæqsæd"
  },
  "intention": {
    "uz": "niyat",
    "uzIPA": "nˈyjæt"
  },
  "decision": {
    "uz": "qaror",
    "uzIPA": "qˈæɾɑɾ"
  },
  "choice": {
    "uz": "tanlov",
    "uzIPA": "tˈænɫɑʋ"
  },
  "chance": {
    "uz": "imkon",
    "uzIPA": "ˈymkɑn"
  },
  "risk": {
    "uz": "tavakkal",
    "uzIPA": "tæʋˈækkæɫ"
  },
  "benefit": {
    "uz": "foyda",
    "uzIPA": "fˈɑjdæ"
  },
  "advantage": {
    "uz": "ustunlik",
    "uzIPA": "ʊstˈʊnɫyk"
  },
  "disadvantage": {
    "uz": "kamchilik",
    "uzIPA": "kæmtSˈyɫyk"
  },
  "experience": {
    "uz": "tajriba",
    "uzIPA": "tædʒɾˈybæ"
  },
  "memory": {
    "uz": "xotira",
    "uzIPA": "χɑtˈyɾæ"
  },
  "attention": {
    "uz": "diqqat",
    "uzIPA": "dˈyqqæt"
  },
  "concentration": {
    "uz": "diqqatni jamlash",
    "uzIPA": "dyqqˈætny dʒˈæmlæʃ"
  },
  "effort": {
    "uz": "sa’y-harakat",
    "uzIPA": "sˈæʔjhæɾˈækæt"
  },
  "progress": {
    "uz": "taraqqiyot",
    "uzIPA": "tˌæɾæqqˈyjɑt"
  },
  "improvement": {
    "uz": "yaxshilanish",
    "uzIPA": "jˌæχʃylˈænyʃ"
  },
  "development": {
    "uz": "rivojlanish",
    "uzIPA": "ɾˌyʋɑdʒlˈænyʃ"
  },
  "growth": {
    "uz": "o‘sish",
    "uzIPA": "ˈosyʃ"
  },
  "achievement": {
    "uz": "yutuq",
    "uzIPA": "jˈʊtʊq"
  },
  "ability": {
    "uz": "qobiliyat",
    "uzIPA": "qˌɑbyɫˈyjæt"
  },
  "talent": {
    "uz": "iste’dod",
    "uzIPA": "ystˈeʔdɑd"
  },
  "potential": {
    "uz": "salohiyat",
    "uzIPA": "sˌæɫɑhˈyjæt"
  },
  "opportunity": {
    "uz": "imkoniyat",
    "uzIPA": "ˌymkɑnˈyjæt"
  },
  "challenge": {
    "uz": "murakkab vazifa",
    "uzIPA": "mʊɾˈækkæb ʋæzˈyfˌæ"
  },
  "difficulty": {
    "uz": "qiyinchilik",
    "uzIPA": "qˌyjyntSˈyɫyk"
  },
  "obstacle": {
    "uz": "to‘siq",
    "uzIPA": "tˈosyq"
  },
  "limit": {
    "uz": "chegara",
    "uzIPA": "tSeɡˈæɾæ"
  },
  "balance": {
    "uz": "muvozanat",
    "uzIPA": "mˌʊʋɑzˈænæt"
  },
  "quality": {
    "uz": "sifat",
    "uzIPA": "sˈyfˌæt"
  },
  "quantity": {
    "uz": "miqdor",
    "uzIPA": "mˈyqdɑɾ"
  },
  "value": {
    "uz": "qadriyat",
    "uzIPA": "qædɾˈyjæt"
  },
  "importance": {
    "uz": "muhimlik",
    "uzIPA": "mʊhˈymɫyk"
  },
  "necessity": {
    "uz": "zarurat",
    "uzIPA": "zæɾˈʊɾæt"
  },
  "possibility": {
    "uz": "ehtimoliy imkoniyat",
    "uzIPA": "ˌehtymˈɑɫyj ˌymkɑnˈyjæt"
  },
  "reality": {
    "uz": "voqelik",
    "uzIPA": "ʋɑqˈeɫyk"
  },
  "truth": {
    "uz": "haqiqat",
    "uzIPA": "hæqˈyqæt"
  },
  "lie": {
    "uz": "yolg‘on",
    "uzIPA": "jˈɑɫʁɑn"
  },
  "fact": {
    "uz": "fakt",
    "uzIPA": "fˈækt"
  },
  "evidence": {
    "uz": "dalil",
    "uzIPA": "dˈæɫyɫ"
  },
  "research": {
    "uz": "tadqiqot",
    "uzIPA": "tædqˈyqɑt"
  },
  "theory": {
    "uz": "nazariya",
    "uzIPA": "nˌæzæɾˈyjæ"
  },
  "method": {
    "uz": "usul",
    "uzIPA": "ˈʊsʊɫ"
  },
  "process": {
    "uz": "jarayon",
    "uzIPA": "dʒæɾˈæjɑn"
  },
  "system": {
    "uz": "tizim",
    "uzIPA": "tˈyzym"
  },
  "structure": {
    "uz": "tuzilma",
    "uzIPA": "tʊzˈyɫmæ"
  },
  "pattern": {
    "uz": "qonuniyat",
    "uzIPA": "qˌɑnʊnˈyjæt"
  },
  "principle": {
    "uz": "tamoyil",
    "uzIPA": "tæmˈɑjyɫ"
  },
  "concept": {
    "uz": "tushuncha",
    "uzIPA": "tʊʃˈʊntSæ"
  },
  "idea": {
    "uz": "g‘oya",
    "uzIPA": "ʁˈɑjæ"
  },
  "thought": {
    "uz": "o‘y",
    "uzIPA": "ˈoj"
  },
  "imagination": {
    "uz": "tasavvur",
    "uzIPA": "tæsˈæʋʋʊɾ"
  },
  "curiosity": {
    "uz": "qiziqish",
    "uzIPA": "qyzˈyqyʃ"
  },
  "responsibility": {
    "uz": "mas’uliyat",
    "uzIPA": "mˌæsʔʊɫˈyjæt"
  },
  "hospitality": {
    "uz": "mehmondo‘stlik",
    "uzIPA": "mˌehmɑndˈostɫyk"
  },
  "perseverance": {
    "uz": "qat’iyat",
    "uzIPA": "qætʔˈyjæt"
  },
  "resilience": {
    "uz": "bardoshlilik",
    "uzIPA": "bˌæɾdɑʃɫˈyɫyk"
  },
  "compassion": {
    "uz": "rahm-shafqat",
    "uzIPA": "ɾˈæhmʃˈæfqˌæt"
  },
  "empathy": {
    "uz": "hamdardlik",
    "uzIPA": "hæmdˈæɾdɫyk"
  },
  "integrity": {
    "uz": "prinsipiallik",
    "uzIPA": "pɾˌynsypyˈæɫɫyk"
  },
  "humility": {
    "uz": "kamtarlik",
    "uzIPA": "kæmtˈæɾɫyk"
  },
  "gratitude": {
    "uz": "minnatdorchilik",
    "uzIPA": "mˌynnætdɑɾtSˈyɫyk"
  },
  "ambition": {
    "uz": "shuhratparastlik",
    "uzIPA": "ʃˌʊhɾætpæɾˈæstɫyk"
  },
  "determination": {
    "uz": "qat’iy qaror",
    "uzIPA": "qˈætʔyj qˈæɾɑɾ"
  },
  "initiative": {
    "uz": "tashabbus",
    "uzIPA": "tæʃˈæbbʊs"
  },
  "innovation": {
    "uz": "yangilik kiritish",
    "uzIPA": "jæŋˈyɫyk kyɾˈytyʃ"
  },
  "ingenuity": {
    "uz": "topqirlik",
    "uzIPA": "tɑpqˈyɾɫyk"
  },
  "insight": {
    "uz": "farosat",
    "uzIPA": "fˌæɾˈɑsæt"
  },
  "foresight": {
    "uz": "oldindan ko‘ra bilish",
    "uzIPA": "ɑɫdˈyndæn kˈoɾæ bˈyɫyʃ"
  },
  "wisdom": {
    "uz": "donolik",
    "uzIPA": "dɑnˈɑɫyk"
  },
  "awareness": {
    "uz": "xabardorlik",
    "uzIPA": "χˌæbæɾdˈɑɾɫyk"
  },
  "consciousness": {
    "uz": "ong",
    "uzIPA": "ˈɑŋ"
  },
  "perception": {
    "uz": "idrok",
    "uzIPA": "ˈydɾɑk"
  },
  "intuition": {
    "uz": "ichki sezgi",
    "uzIPA": "ˈytSky sˈezɡy"
  },
  "assumption": {
    "uz": "taxmin",
    "uzIPA": "tˈæχmyn"
  },
  "hypothesis": {
    "uz": "gipoteza",
    "uzIPA": "ɡˌypɑtˈezæ"
  },
  "conclusion": {
    "uz": "xulosa",
    "uzIPA": "χʊɫˈɑsæ"
  },
  "interpretation": {
    "uz": "talqin",
    "uzIPA": "tˈæɫqyn"
  },
  "evaluation": {
    "uz": "baholash",
    "uzIPA": "bæhˈɑlæʃ"
  },
  "assessment": {
    "uz": "ekspert bahosi",
    "uzIPA": "ˈekspeɾt bæhˈɑsy"
  },
  "criterion": {
    "uz": "mezon",
    "uzIPA": "mˈezɑn"
  },
  "perspective": {
    "uz": "nuqtai nazar",
    "uzIPA": "nʊqtˈæy nˈæzæɾ"
  },
  "approach": {
    "uz": "yondashuv",
    "uzIPA": "jɑndˈæʃʊʋ"
  },
  "strategy": {
    "uz": "strategiya",
    "uzIPA": "stɾˌæteɡˈyjæ"
  },
  "implementation": {
    "uz": "amalga oshirish",
    "uzIPA": "æmˈæɫɡæ ɑʃˈyɾyʃ"
  },
  "execution": {
    "uz": "ijro",
    "uzIPA": "ˈydʒɾɑ"
  },
  "coordination": {
    "uz": "muvofiqlashtirish",
    "uzIPA": "mˌʊʋɑfˌyqlæʃtˈyɾyʃ"
  },
  "collaboration": {
    "uz": "hamkorlik",
    "uzIPA": "hæmkˈɑɾɫyk"
  },
  "negotiation": {
    "uz": "muzokaralar",
    "uzIPA": "mˌʊzɑkæɾˈælæɾ"
  },
  "compromise": {
    "uz": "murosa",
    "uzIPA": "mʊɾˈɑsæ"
  },
  "consensus": {
    "uz": "yakdillik",
    "uzIPA": "jækdˈyɫɫyk"
  },
  "controversy": {
    "uz": "munozara",
    "uzIPA": "mˌʊnɑzˈæɾæ"
  },
  "dilemma": {
    "uz": "ikkilanish",
    "uzIPA": "ˌykkylˈænyʃ"
  },
  "contradiction": {
    "uz": "ziddiyat",
    "uzIPA": "zyddˈyjæt"
  },
  "ambiguity": {
    "uz": "ko‘p ma’nolilik",
    "uzIPA": "kˈop mˌæʔnɑɫˈyɫyk"
  },
  "uncertainty": {
    "uz": "noaniqlik",
    "uzIPA": "nˌɑænˈyqɫyk"
  },
  "inevitability": {
    "uz": "muqarrarlik",
    "uzIPA": "mˌʊqæɾɾˈæɾɫyk"
  },
  "consequence": {
    "uz": "oqibat",
    "uzIPA": "ɑqˈybæt"
  },
  "implication": {
    "uz": "nazarda tutilgan ma’no",
    "uzIPA": "næzˈæɾdæ tʊtˈyɫɡæn mˈæʔnɑ"
  },
  "influence": {
    "uz": "ta’sir",
    "uzIPA": "tˈæʔsyɾ"
  },
  "impact": {
    "uz": "ta’sir ko‘rsatish",
    "uzIPA": "tˈæʔsyɾ koɾsˈætyʃ"
  },
  "contribution": {
    "uz": "hissa",
    "uzIPA": "hˈyssæ"
  },
  "commitment": {
    "uz": "sodiqlik",
    "uzIPA": "sɑdˈyqɫyk"
  },
  "obligation": {
    "uz": "majburiyat",
    "uzIPA": "mˌædʒbʊɾˈyjæt"
  },
  "accountability": {
    "uz": "hisobdorlik",
    "uzIPA": "hˌysɑbdˈɑɾɫyk"
  },
  "transparency": {
    "uz": "shaffoflik",
    "uzIPA": "ʃæffˌɑfɫˈyk"
  },
  "sustainability": {
    "uz": "barqaror rivojlanish",
    "uzIPA": "bæɾqˈæɾɑɾ ɾˌyʋɑdʒlˈænyʃ"
  },
  "efficiency": {
    "uz": "xarajatlar samaradorligi",
    "uzIPA": "χˌæɾædʒˈætlæɾ sˌæmæɾˌædɑɾɫˈyɡy"
  },
  "productivity": {
    "uz": "unumdorlik",
    "uzIPA": "ˌʊnʊmdˈɑɾɫyk"
  },
  "profitability": {
    "uz": "daromadlilik",
    "uzIPA": "dˌæɾɑmædɫˈyɫyk"
  },
  "scarcity": {
    "uz": "tanqislik",
    "uzIPA": "tænqˈysɫyk"
  },
  "abundance": {
    "uz": "mo‘l-ko‘llik",
    "uzIPA": "mˈoɫkˈoɫɫyk"
  },
  "prosperity": {
    "uz": "farovonlik",
    "uzIPA": "fˌæɾɑʋˈɑnɫyk"
  },
  "poverty": {
    "uz": "kambag‘allik",
    "uzIPA": "kˌæmbæʁˈæɫɫyk"
  },
  "inequality": {
    "uz": "tengsizlik",
    "uzIPA": "teŋsˈyzɫyk"
  },
  "prejudice": {
    "uz": "xurofot",
    "uzIPA": "χʊɾˈɑfˌɑt"
  },
  "discrimination": {
    "uz": "kamsitish",
    "uzIPA": "kæmsˈytyʃ"
  },
  "diversity": {
    "uz": "xilma-xillik",
    "uzIPA": "χˈyɫmæχˈyɫɫyk"
  },
  "inclusion": {
    "uz": "barchani jalb etish",
    "uzIPA": "bæɾtSˈæny dʒˈæɫb ˈetyʃ"
  },
  "integration": {
    "uz": "integratsiya",
    "uzIPA": "ˌynteɡɾætsˈyjæ"
  },
  "adaptation": {
    "uz": "moslashuv",
    "uzIPA": "mɑslˈæʃʊʋ"
  },
  "transformation": {
    "uz": "o‘zgarish",
    "uzIPA": "ozɡˈæɾyʃ"
  },
  "transition": {
    "uz": "o‘tish",
    "uzIPA": "ˈotyʃ"
  },
  "revolution": {
    "uz": "inqilob",
    "uzIPA": "ynqˈyɫɑb"
  },
  "evolution": {
    "uz": "evolyutsiya",
    "uzIPA": "ˌeʋɑɫjʊtsˈyjæ"
  },
  "civilization": {
    "uz": "sivilizatsiya",
    "uzIPA": "sˌyʋyɫˌyzætsˈyjæ"
  },
  "heritage": {
    "uz": "meros",
    "uzIPA": "mˈeɾɑs"
  },
  "legacy": {
    "uz": "qoldirilgan meros",
    "uzIPA": "qˌɑɫdyɾˈyɫɡæn mˈeɾɑs"
  },
  "identity": {
    "uz": "o‘ziga xoslik",
    "uzIPA": "ozˈyɡæ χˈɑsɫyk"
  },
  "sovereignty": {
    "uz": "suverenitet",
    "uzIPA": "sˌʊʋeɾenˈytet"
  },
  "democracy": {
    "uz": "demokratiya",
    "uzIPA": "dˌemɑkɾætˈyjæ"
  },
  "bureaucracy": {
    "uz": "byurokratiya",
    "uzIPA": "bjˌʊɾɑkɾætˈyjæ"
  },
  "legislation": {
    "uz": "qonunchilik",
    "uzIPA": "qˌɑnʊntSˈyɫyk"
  },
  "jurisdiction": {
    "uz": "yurisdiksiya",
    "uzIPA": "jˌʊɾysdyksˈyjæ"
  },
  "constitution": {
    "uz": "konstitutsiya",
    "uzIPA": "kˌɑnstytʊtsˈyjæ"
  },
  "amendment": {
    "uz": "qonunga tuzatish",
    "uzIPA": "qɑnˈʊŋæ tʊzˈætyʃ"
  },
  "regulation": {
    "uz": "me’yoriy qoida",
    "uzIPA": "meʔjˈɑɾyj qɑˈydæ"
  },
  "compliance": {
    "uz": "talablarga rioya qilish",
    "uzIPA": "tˌælæblˈæɾɡæ ɾyˈɑjæ qˈyɫyʃ"
  },
  "violation": {
    "uz": "qoidabuzarlik",
    "uzIPA": "qˌɑydˌæbʊzˈæɾɫyk"
  },
  "litigation": {
    "uz": "sud muhokamasi",
    "uzIPA": "sˈʊd mˌʊhɑkæmˈæsy"
  },
  "reconciliation": {
    "uz": "yarashuv",
    "uzIPA": "jæɾˈæʃʊʋ"
  },
  "rehabilitation": {
    "uz": "reabilitatsiya",
    "uzIPA": "ɾˌeæbˌyɫytætsˈyjæ"
  },
  "restoration": {
    "uz": "tiklash",
    "uzIPA": "tˈyklæʃ"
  },
  "preservation": {
    "uz": "saqlash",
    "uzIPA": "sˈæqlæʃ"
  },
  "conservation": {
    "uz": "tabiatni muhofaza qilish",
    "uzIPA": "tˌæbyˈætny mˌʊhɑfˌæzæ qˈyɫyʃ"
  },
  "biodiversity": {
    "uz": "biologik xilma-xillik",
    "uzIPA": "bˌyɑɫˈɑɡyk χˈyɫmæχˈyɫɫyk"
  },
  "ecosystem": {
    "uz": "ekotizim",
    "uzIPA": "ˌekɑtˈyzym"
  },
  "habitat": {
    "uz": "yashash muhiti",
    "uzIPA": "jˈæʃæʃ mʊhˈyty"
  },
  "extinction": {
    "uz": "qirilib ketish",
    "uzIPA": "qyɾˈyɫyb kˈetyʃ"
  },
  "pollution": {
    "uz": "ifloslanish",
    "uzIPA": "yfɫˌɑslˈænyʃ"
  },
  "emission": {
    "uz": "chiqarib tashlash",
    "uzIPA": "tSyqˈæɾyb tˈæʃlæʃ"
  },
  "renewable": {
    "uz": "qayta tiklanadigan",
    "uzIPA": "qˈæjtæ tˌyklænædˈyɡæn"
  },
  "biodegradable": {
    "uz": "biologik parchalanadigan",
    "uzIPA": "bˌyɑɫˈɑɡyk pˌæɾtSælˌænædˈyɡæn"
  },
  "interdependence": {
    "uz": "o‘zaro bog‘liqlik",
    "uzIPA": "ozˈæɾɑ bɑʁɫˈyqɫyk"
  }
};
